brian-team/brian2

- brian2/codegen/generators/base.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/tests/test_neurongroup.py
This fixes some issues around linking variables from a group of size one, including the problem with writing to them in reset statements as described on the mailing list: https://groups.google.com/forum/#!topic/brian-development/13FQouRZz78
Also adds the corresponding tests.
> Linked var fixes

- brian2/codegen/_prefs.py
- brian2/codegen/translation.py
As the title says... I briefly looked into making this an attribute of the `Device`, but we apply the optimisations in `make_statements` which is an early function that does not yet know about code generation targets, devices, etc. so it seemed wrong to introduce such a dependence there. The preference is quite straightforward and it can also be a useful future workaround if we encounter further issues with the mechanism, i.e. we can just tell users to switch it off until we fix the problem.
> Make the "loop-invariant optimisations" optional via a preference

- brian2/synapses/synapses.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_synapses.py
Does what the title says. As discussed in #348, this only deals with the error case. Warnings about clashes between pre- and postsynaptic variables are still up for discussion (see #406)
> Raise an error if the name of a synaptic variable clashes with a pre- or postsynaptic variable name

- brian2/codegen/_prefs.py
- brian2/codegen/codeobject.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/devices/device.py
- brian2/tests/test_codegen.py
This implements the mechanism we discussed in #379. I implemented the determination whether weave/cython works with a little code snippet that will be compiled. This can indeed take a considerable time (on the order of 3-5s if done from scratch without any caches) but I don't think this is a problem because:
1. This is only done if `'auto'` is actually used, i.e. it doesn't take any time if you explicitly set a codegen target
2. In most cases where a target is not available (e.g. Python 3 for weave, or no Cython installation), we don't even get that far
3. Most importantly: weave and Cython cache their codes on disk automatically already, i.e. when this has been executed once on a machine it is basically instantaneous the next time
I didn't realize this before but point 3 does really take …
> Auto codegen target

- brian2/devices/cpp_standalone/device.py
- brian2/devices/device.py
- brian2/tests/__init__.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_equations.py
- brian2/tests/test_functions.py
- brian2/tests/test_monitor.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_poissongroup.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spatialneuron.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_stateupdaters.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_synapses.py
- brian2/tests/test_thresholder.py
- brian2/tests/test_timedarray.py
- brian2/tests/test_utils.py
- dev/tools/run_nose_tests_long_and_standalone.py
- dev/tools/run_nose_tests_standalone.py
- docs_sphinx/conf.py
- docs_sphinx/developer/guidelines/testing.rst
This introduces a new category of tests, "standalone-compatible" tests. In addition to tests marked as `@attr('cpp_standalone')` (renamed from the previous `standalone`), tests can be marked as `@attr('standalone-compatible')`. They are then executed with the new `CPPStandaloneSimpleDevice` which directly calls `build` after a run. Unfortunately, nose does not offer a mechanism to simply call a teardown function after every single test, so "standalone-compatible" tests also have to use `with_setup(teardown=restore_device)`. From my side this is ready to merge.
BTW: The `cpp_standalone_simple` device could also be useful for users in general (you don't have to add a `device.build` call for simple simulations), I wonder whether we should advertise this use case.
> Standalone tests

- brian2/groups/neurongroup.py
- brian2/spatialneuron/spatialneuron.py
- brian2/stateupdaters/base.py
- brian2/synapses/synapses.py
- brian2/tests/test_stateupdaters.py
- docs_sphinx/advanced/state_update.rst
- docs_sphinx/user/models.rst
Now, each object defines its own list of algorithms that are tried in order. Closes #351 
Well, I think that's all we wanted to do. It's straightforward and easy to explain and it also avoids the use of the fragile `'independent'` state updater without a user explicitly asking for it.
> Change the system that decides which state updater algorithm is used

- brian2/__init__.py
- brian2/core/core_preferences.py
- docs_sphinx/user/import.rst
Does what the title says. I did not find a simple straightforward way to share the dependency information with `setup.py`, but I think given that we change our dependencies quite rarely, it isn't really worth the effort of coming up with an elaborate system.
> Check dependency versions at runtime

- brian2/codegen/runtime/cython_rt/templates/spikegenerator.pyx
- brian2/codegen/runtime/numpy_rt/templates/spikegenerator.py_
- brian2/codegen/runtime/weave_rt/templates/spikegenerator.cpp
- brian2/devices/cpp_standalone/templates/spikegenerator.cpp
- brian2/tests/test_spikegenerator.py
I changed the algorithm slightly, and now I'm getting correct rounding behaviour for spike times at multiples of dt for long simulations. I added two tests that check this, they take quite some time to run and are therefore only tested when running the long test suite.
@thesamovar Could you run the long test suite on your machine and merge if it passes -- our automatic testing on travis and appveyor will not run those tests.
> Small change to the algorithm for `SpikeGeneratorGroup`

- brian2/codegen/runtime/cython_rt/templates/common.pyx
Just added the ``infer_types=True`` argument for Cython. This can sometimes improve the quality of the generated C++ code (avoiding Python calls).
> Use type inference support for Cython

- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/core/functions.py
- brian2/tests/test_functions.py
- docs_sphinx/user/functions.rst
Well, does what the title says. I needed a `sign` function (returning -1, 0 or 1) and did not want to fiddle around with complicated `int(...)` expressions.
From my side, it's ready to merge.
> Add a `sign` function

- brian2/__init__.py
- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/spatialneuron/spatialneuron.py
- brian2/tests/__init__.py
- brian2/tests/test_parsing.py
- brian2/utils/logger.py
- setup.py
In this branch, I added a pure-numpy implementation of the `spatialstateupdate` template, i.e. one that does not use `solve_banded` from scipy. This was the only place in the code where we used scipy and listing it as a dependency meant that users installing brian via pip or easy_install had to download the full 10MB source code and wait for its compilation to finish (which takes a couple of minutes).
The problem is that the algorithm is really straightforward to implement in C (i.e., with loops) but its forward and backward passes over arrays are not vectoriseable using numpy syntax (at least I don't know how). Therefore, even after a bit of optimisation, the numpy solution is very slow -- about 10x as slow as the version using scipy... I therefore thought that the best approach is to:
* …
> Scipy removal

- brian2/codegen/runtime/cython_rt/templates/spikemonitor.pyx
- brian2/codegen/runtime/weave_rt/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
For subgroups not starting at 0, the code for searching through the list of all spikes for spikes that should be recorded was not correct. If some neuron in the full group spiked, but none of them >= the start index of the recorded subgroup, then all (instead of none) spikes were recorded. The good news is that this should not have led to undetected incorrect recordings because 1) it would have recorded spikes with negative indices, which would be incorrect in an obvious way and 2) it most of the time should have led to a segmentation fault due to accessing the `_count` array with negative indices (this is the way I encountered the issue). Nevertheless, an important bug.
> Fix SpikeMonitor for subgroups (weave, cython, cpp_standalone)

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/objects.cpp
- brian2/tests/__init__.py
Arrays were previously stored in the results directory using the name of the array as the filename. On file systems that are not case sensitive (e.g. Windows), this is not guaranteed to work. The most common situation were this leads to problems is with a variable "I" in a neuron group, since it also contains the variable "i" by default. As an easy fix, the filename now uses the name of the variable plus its hash value. Note that users should never have to construct such file names manually, if for any reasons they cannot access the values via the normal state variable mechanism, they should use `device.get_array_filename` to get the filename.
> Use filenames that are guaranteed to be unique for standalone

- .travis.yml
- MANIFEST.in
- brian2/sphinxext/generate_examples.py
This includes `conf.py` and the example files in the release tarball (increasing its size from 487KB to 517KB, which is not a big deal I think). This will allow to build the documentation (using something like `sphinx-build docs_sphinx target_dir`) from the release tarball. Previously, we did include the documentation from `docs_sphinx` but you could not actually build the docs. The generated docs will not be exactly like the docs on http://brian2.readthedocs.org, since the example images are not included and neither are the tutorials -- but clearly we don't want to include them in the release tarball and I don't think providing a separate `brian2-doc` package is worth the effort, given that readthedocs allows  you to download the complete documentation for offline use.
Thanks again to …
> Build docs from release

- brian2/codegen/cpp_prefs.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/cython_rt/templates/common.pyx
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/devices/cpp_standalone/templates/group_variable_set_conditional.cpp
- brian2/devices/cpp_standalone/templates/main.cpp
- brian2/devices/cpp_standalone/templates/makefile
- brian2/devices/cpp_standalone/templates/run.cpp
- brian2/devices/cpp_standalone/templates/synapses_classes.cpp
- brian2/devices/cpp_standalone/templates/win_makefile
- brian2/synapses/cspikequeue.cpp
- brian2/synapses/cythonspikequeue.pyx
- brian2/tests/__init__.py
- docs_sphinx/advanced/index.rst
- docs_sphinx/advanced/interface.rst
- docs_sphinx/user/functions.rst
- docs_sphinx/user/input.rst
- examples/advanced/opencv_movie.py
This branch introduces more options to customize the compilation for standalone (useful to interface with external libraries) and also tries to use a consistent interface for cython, weave and standalone. The preferences in `codegen.cpp` now allow:
* to add include, library and runtime library directories
* to add libraries (e.g. adding `mylibrary` will link with `-lmylibrary` on Linux)
* to include additional headers in all files that contain user code
* to define macros
* to add additional linker arguments
I tried to use the general distutils mechanism to generate the compiler/linker options also for standalone (in the same way as it is done for weave and cython), this might buy us support for additional compilers etc. in the future.
There's a new example …
> Standalone customization

- brian2/core/variables.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/device.py
- brian2/synapses/cspikequeue.cpp
- brian2/synapses/spikequeue.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
In standalone mode, you could previously not use `Synapses(..., delay=1*ms)`, which sets a scalar delay for all synapses. Also, setting a scalar delay in this way was very inefficient because at the initialization phase of the C version of the spike queue, this delay was always stored once per synapse (see #169).
This pull request fixes those two issues, scalar delays are now stored as single values and they work for standalone as well (this also makes the "Brunel_Hakim_1999.py" and "Sturzl_et_al_2000.py" examples work in standalone mode now).
> Scalar delays in standalone

- brian2/groups/neurongroup.py
- brian2/tests/test_network.py
- brian2/tests/test_neurongroup.py
Closes #460
This is a trivial fix that simply removes the lines that stated the used state update method from the HTML output of a `NeuronGroup`. The state update method is not necessarily fixed at this point yet and I don't think getting it to work here for the cases when it is (the user explicitly provided a `method` argument) is worth the effort.
> [MRG] Fix (and test) the HTML representation for `NeuronGroup`

- brian2/core/operations.py
- brian2/tests/test_network.py
- brian2/units/fundamentalunits.py
- docs_sphinx/user/input.rst
Not a very important feature, but in more complex frameworks it might be useful to have a network operation that accesses some parent object state via `self`. This pull request fixes this issue but more importantly does more strict error checking (before, an instance method with the `self` argument would be interpreted as a function with a single argument, i.e. the current time was passed as `self`, and functions with more than one argument did not raise an error until executed).
Closes #474
> [MRG] Allow instance methods as network operations

- brian2/codegen/runtime/cython_rt/templates/statemonitor.pyx
- brian2/codegen/runtime/weave_rt/templates/statemonitor.cpp
- brian2/core/variables.py
- brian2/devices/device.py
- brian2/memory/dynamicarray.py
- brian2/monitors/statemonitor.py
This branch improves the performance of the resize operation for dynamic arrays quite significantly (in a long running complex example the time for `statemonitor` went down from 45s to 17s). It mostly does it by including a special function for resizing along the first dimension for multi-dimensional arrays.
I briefly played around with storing the size of the underlying data array in a separate variable (so that the weave code can directly check whether a resize is necessary), but this makes things very fragile because not calling `resize` also means that the numpy array view on the underlying data has the wrong size, so we have to update this in the end of the run, etc. I got the impression that it is easy to introduce hard-to-debug problems (say a user wants to access the data stored …
> [MRG] Faster resize for dynamic array

- brian2/monitors/statemonitor.py
- brian2/tests/test_monitor.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/changes.rst
- docs_sphinx/user/recording.rst
Also adds a convenience method for recording at the end.
Updates tests and documentation, ready-to-merge from my side.
Closes #452
> [MRG] Let `StateMonitor` record in the start slot by default

- brian2/groups/group.py
- brian2/monitors/statemonitor.py
- brian2/tests/test_monitor.py
- brian2/tests/test_neurongroup.py
- docs_sphinx/user/models.rst
- docs_sphinx/user/recording.rst
...aaand this is ready to merge as well. It makes the `get_states` method more useful, in particular it fixes it for `StateMonitor`. This is a small detail but it makes it much easier to dump everything that a `StateMonitor` recorded to disk, which is something that quite a few users want to do, I think.
> [MRG] `get_states` improvements

- brian2/codegen/runtime/cython_rt/templates/spikemonitor.pyx
- brian2/codegen/runtime/numpy_rt/templates/spikemonitor.py_
- brian2/codegen/runtime/weave_rt/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
- brian2/monitors/spikemonitor.py
- brian2/tests/test_monitor.py
- docs_sphinx/user/recording.rst
Do not record them with `record=False`.
Closes #510
Unfortunately this will break templates for other devices (CC @tnowotny @moritzaugustin @Kwartke). For full support (including the new support for recording arbitrary variables introduced with #498), the templates have to be adapted analogue to the C++ standalone templates. Alternatively, a quick fix would be to raise a `NotImplementedError` if `SpikeMonitor.record` is False and/or `SpikeMonitor.record_variables` is not simply `{'i', 't'}`.
> [MRG] Treat `i` and `t` in the same way as other variables in `StateMonitor`

- brian2/core/magic.py
- brian2/core/network.py
- brian2/groups/group.py
- brian2/tests/test_network.py
This allows to conveniently get/set the states for all objects in a network. This is related to #29 but it is not a solution for it (see my comment there).
> [MRG] Provide `get_states`/`set_states`  methods for networks

- .travis.yml
- brian2/core/core_preferences.py
- brian2/tests/test_functions.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_stateupdaters.py
- brian2/tests/test_synapses.py
- dev/conda-recipe/bld.bat
- dev/conda-recipe/build.sh
- dev/conda-recipe/meta.yaml
- examples/adaptive_threshold.py
Somehow my changes for these two separate issues ended up in the same branch, but I think it's fine because they're both small changes. For float32 it's very simple, no more comment needed I think. When this is merged we can remove the 2.0 milestone for issue #417 but not close it. Detailed comments for long to short tests below.
I changed some tests from long to short. Here are the test timings on my computer. All times include compilation from scratch for numpy/weave/cython. The ones I changed are marked with CHANGED TO SHORT. Some tests probably don't need to be run for all of numpy/weave/cython, and I've marked those with ONLY NEEDS ONE. Perhaps we could have a new attr like 'long-for-cython', etc.
Total time added on my machine: ~9m. That's quite annoying I guess but it's valuable …
> [MRG] Change some tests from long to short and raise error for float32

- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/runtime/cython_rt/templates/common.pyx
- brian2/core/functions.py
- brian2/parsing/rendering.py
- brian2/parsing/sympytools.py
- brian2/tests/test_functions.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_parsing.py
Needed to change the handling of mod, previously sympy was converting it to Mod and thence to mod. I found a workaround to get a single function to work for both integers and floats in C++ but not in Cython. So I changed it so that mod is left as % and now CPPNodeRenderer converts this to _brian_mod, which is always put into the support code (I created a new attribute universal_support_code to put things that are always in the support code).
Ready to merge if the tests pass (they do on my win64 machine).
Fixes #509. Fixes #286.
> [MRG] Better support for mod operation with mixed types

- brian2/core/names.py
- brian2/core/network.py
- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_base.py
- brian2/tests/test_cpp_standalone.py
For wildcard names, the same mechanism as before is used but explicitly given names are not checked for uniqueness at creation time. Instead, `Network.before_run` checks that all names within the network are unique. In addition, `CPPStandaloneDevice.build` checks that names are globally unique. Closes #216 
This should be particularly useful in interactive consoles and ipython notebooks whenever explicit names for objects are used. Should also make @owenmackwood happy.
> [MRG] Allow multiple objects with the same name at creation time

- brian2/core/variables.py
This is a trivial fix to make getting `group.var[:]` use `slice(None)` instead of `np.arange(len(group))` for indexing, it makes indexing in these cases (which will also be triggered by simple `group.var` usages) significantly faster (though it will not have any measurable impact on the performance most likely). I had a look at implementing an improvement for setting variables as well (as stated in #195) but decided against it: it's somewhat complicated and would mean changes to templates (with different code generated depending on the kind of indexing). All that for a questionable gain, setting a variable of a group of a million neurons only takes milliseconds to complete as it is...
Closes #195
> [MRG] Special case the getting of all values of a state variable

- brian2/core/functions.py
- brian2/core/variables.py
- brian2/equations/unitcheck.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/synapses/synapses.py
- brian2/tests/test_neurongroup.py
- brian2/units/fundamentalunits.py
This should give significantly better error messages for unit mismatches, e.g. instead of
```Python
>>> 3*mV + 1*mV + 3*ms
...
DimensionMismatchError: Addition, dimensions were (m^2 kg s^-3 A^-1) (s)
```
you'll now get
```Python
DimensionMismatchError: Cannot calculate 4. mV + 3. ms, units do not match (units are volt and second).
```
Instead of 
```Python
DimensionMismatchError: exp, dimensions were (m^2 kg s^-3 A^-1) (1)
```
you get
```Python
DimensionMismatchError: exp expects a dimensionless argument but got -70. mV (unit is volt).
```
and instead of
```Python
>>> G = NeuronGroup(1000, 'v : volt')
>>> G.v = np.arange(1000)*mA
...
DimensionMismatchError: Incorrect units for setting v, dimensions were (A) (m^2 kg s^-3 A^-1)
```
you get
```Python
DimensionMismatchError: v should be set …
```
> [MRG] Better unit errors

- .travis.yml
- brian2/tests/test_cpp_standalone.py
Seems to work fine, we should have some conda packages of the latest development version after it has been merged into master. I did not bother with getting OpenMP to run.
I'll take the liberty to merge this myself right away, not much to review here.
> Enable tests for MacOSX

- brian2/devices/cpp_standalone/codeobject.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/devices/cpp_standalone/templates/network.cpp
- brian2/devices/cpp_standalone/templates/synapses.cpp
This has two small fixes to the OpenMP support: in the synapses template, every code that used a scalar variable incorrectly triggered the use of the single-thread code (affecting the post code in STDP). The second fix is to use `omp_get_wtime` instead of `std::clock` to count runtimes, this avoid the weird profiling results and makes it unnecessary to divide by number of threads etc.
It's all fairly simple changes and it would be ready to merge but the OpenMP test now apparently no longer compiles on Windows. @thesamovar could you have a look at it? It does not give any helpful output in the log and trying to figure this out in my Windows VM is way too annoying for a Friday evening...
> [MRG] Fix OpenMP profiling

- brian2/groups/neurongroup.py
- brian2/spatialneuron/spatialneuron.py
- brian2/stateupdaters/__init__.py
- brian2/stateupdaters/explicit.py
- brian2/synapses/synapses.py
- brian2/tests/test_stateupdaters.py
- docs_sphinx/user/models.rst
Here we have added the stochastic Heun method as a StateUpdateMethod. A description can be found in [sde tutorial](http://infoscience.epfl.ch/record/143450/files/sde_tutorial.pdf). It was tested with the [sde test example](https://brian2.readthedocs.org/en/2.0b4/examples/advanced.stochastic_odes.html). The results are comparable to the Milstein method:
> Heun stateupdater

- brian2/equations/codestrings.py
- brian2/stateupdaters/explicit.py
This branch contains a few improvements for dealing with complex, in particular stochastic, equations. In `Expression.split_stochastic`, the use of sympy's `expand` could result in very big strings that made everything slow and could even lead to memory errors (for the example provided on the mailing list https://groups.google.com/d/topic/brian-development/fL8wfggCMrw/discussion it resulted into a > 2MB string...). I removed the `expand` and also replaced the quite demanding `match` by a simple `collect`, it seems to work fine. The branch also contains a few smaller improvements that should avoid a few unnecessary sympy operations.
> [MRG] Improve stochastic parsing

- brian2/units/__init__.py
- docs_sphinx/user/units.rst
Small change, but `mole` etc. is quite often used for concentration of ions in complex models, importing it explicitly is kind of annoying.
> [MRG] Add `mole` (and `umole` etc.) to the list of units imported by default

- brian2/codegen/runtime/cython_rt/templates/statemonitor.pyx
- brian2/codegen/runtime/weave_rt/templates/statemonitor.cpp
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/statemonitor.cpp
- brian2/tests/test_monitor.py
This uses the `Variable` object itself to resize the dynamic array in state monitor. This is slightly slower than using `DynamicArray.resize` but it will update the `Variable.size` attribute as well, which is important, especially for the `store`/`restore` mechanism (which was broken for Cython and weave).
Fixes #518
> [MRG] Resize variables correctly in `StateMonitor`

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
> [MRG] Check that source/target indicies provided to `Synapses.connect` lie within the correct range

- brian2/codegen/codeobject.py
- brian2/monitors/statemonitor.py
- docs_sphinx/user/synapses.rst
- examples/synapses/nonlinear.py
This also updates the documentation and makes another error message slightly nicer (which occurs if you do something like `StateMonitor(synapses, ..., record=synapses['i==0'])` in standalone).
> [MRG] Better error message for `StateMonitor(synapses, ..., record=True)` in standalone

- brian2/utils/logger.py
Trivial fix, but without it any kind of exception that is raised in `std_silent.close` will lead to a `NameError`, because `WindowsError` does not exist on Linux/MacOS. We want to ignore those exceptions anyway, so just replacing it with `OSError` should be fine (`WindowsError` derives from `OSError`).
Fixes #555
> [MRG] Catch `OSError` instead of `WindowsError` when closing `std_silent` 

- brian2/devices/cpp_standalone/templates/spatialstateupdate.cpp
- brian2/synapses/cspikequeue.cpp
- brian2/tests/__init__.py
- brian2/tests/test_spatialneuron.py
This fixes #568, but I also realized two more issues along the road:
* The standalone-compatible tests that were supposed to run with OpenMP were actually not running with it (except for the first one)...
* Fixing the above revealed memory errors in some tests which had a single synapse
I also removed the long attribute from three multicompartmental neuron tests that aren't that time-consuming (they would have caught #568).
> [MRG] Fixes for OpenMP

- brian2/groups/group.py
- brian2/synapses/synapses.py
- brian2/tests/test_monitor.py
- brian2/tests/test_morphology.py
- brian2/tests/test_spatialneuron.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_units.py
- brian2/units/unitsafefunctions.py
This should fix brian2 for use with the latest numpy release. Note that the test servers are not yet using numpy 0.10 because packages depending on numpy (scipy mostly, I think) are not updated yet on conda. I think this should change in the next days, though.
The test suite showed quite a number of errors with numpy 0.10, luckily most of them were problems in the test suite, brian itself should work mostly fine (except for `linspace`, see below). Most important changes:
* `assert_allclose` removed units in previous numpy versions, so some tests were sloppy about them (also, you cannot compare e.g. `np.arange(3)*mV` to `[0*mV, 1*mV, 2*mV]`, you'll have to use `[0, 1, 2]*mV` or `Quantity([0*mv, 1*mV, 2*mV])` for the latter).
* comparing `x == 'string'` raises a warning if `x` is a numpy …
> [MRG] Fixes for numpy 0.10

- brian2/__init__.py
- brian2/codegen/generators/cython_generator.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/cython_rt/templates/common.pyx
- brian2/stateupdaters/exact.py
- brian2/synapses/spikequeue.py
- brian2/tests/test_complex_examples.py
- brian2/tests/test_functions.py
- brian2/tests/test_neurongroup.py
- examples/CUBA.py
The previous merge left one test failure unfixed, this should now work (tests are now using numpy 0.10 on our test servers as well). I also fixed a warning in the Python spike queue.
There's one more issue, though. After removing the `codegen-independent` label from `test_cuda`, this now fails on Cython. The reason is a division by zero (that also raises a warning on numpy). I think this problem appears only now because the CUDA example can now use the exact integration and boolean variables are taken into account for the loop-invariant constants. The problem arises for the conductances `ge` and `gi` during the refractory period:
```Python
_lio_const_5 = (dt * (taue - taum)) * _int(0.0)
_lio_const_6 = ((dt * (taue - taum)) * _int(1.0)) - ((dt * (taue - taum)) * _int(0.0))
_ge = (((((- ge) …
```
> [MRG] More fixes for numpy 0.10

- .travis.yml
- brian2/devices/cpp_standalone/templates/summed_variable.cpp
- brian2/synapses/spikequeue.py
- brian2/tests/test_synapses.py
I did not look into the issue in detail yet, but this branch includes an extended `test_transmission` test that fails with the Python spike queue.
(BTW: This test only tests transmission with one-to-one synapses, we should at least have tests for many-to-one and one-to-many connections as well).
> [MRG] Fix Python spike queue

- brian2/codegen/generators/cython_generator.py
- brian2/codegen/runtime/cython_rt/templates/common.pyx
- brian2/codegen/runtime/cython_rt/templates/spatialstateupdate.pyx
- brian2/codegen/runtime/cython_rt/templates/spikegenerator.pyx
- brian2/codegen/runtime/weave_rt/templates/group_get_indices.cpp
- brian2/codegen/runtime/weave_rt/templates/group_variable_get_conditional.cpp
- brian2/codegen/runtime/weave_rt/templates/group_variable_set_conditional.cpp
- brian2/codegen/runtime/weave_rt/templates/stateupdate.cpp
- brian2/tests/__init__.py
- brian2/tests/test_synapses.py
- dev/conda-recipe/meta.yaml
I noticed that there were a few bugs which even made some examples no longer work with weave (all related to getting rid of `AttributeVariable` for `N`). None of these problems were caught by the test suite, mostly because they were in the templates that are used for expressions such as `G.v['i%2 == 0'] = -70*mV` and by default we execute them in numpy, since the compilation often takes longer than running the code in such simple cases. Now when the tests are run, also these simple statements are using the tested code generation target. I also added one small test and included `bsddb` in the run-time dependencies for the conda package which should make the issue with inefficient weave under anaconda go away (#577).
Nothing too spectacular in this branch, ready to merge from my side.
> [MRG] Weave fixes

- brian2/core/magic.py
- brian2/core/network.py
- brian2/groups/group.py
- brian2/input/spikegeneratorgroup.py
- brian2/synapses/cspikequeue.cpp
- brian2/synapses/cythonspikequeue.pyx
- brian2/synapses/spikequeue.py
- brian2/synapses/synapses.py
- brian2/tests/test_network.py
- docs_sphinx/user/running.rst
There's still a bit of documentation and testing missing, but the basic functionality is there. The `store/restore` mechanism now takes an optional `filename` argument, allowing you to store the state to disk instead of to memory. It internally uses a `_full_state` method that returns a dictionary of the values of all the state variables of the object (for `SynapticPathway`, it also contains a representation of the internal state of the spike queue). There is some redundancy with the `get_state` method here, but I'd prefer them to stay separate, the `get_state` method is something for the user which focuses on usability instead of completeness. 
The spike queue part is not quite working yet but the current test does not catch it.
> [MRG] Store state to disk

- brian2/synapses/cspikequeue.cpp
In the C++ spike queue, treat potentially heterogeneous delays as homogeneous if they are all the same (as in the Python spike queue)
Closes #561 
This does not make an enormous speed difference but still. Talking about speed differences: I used the CUBA example and noticed it was quite slow. This was because I did not have the `-ffast-math` switch on -- it makes the state updater several times faster (which does somewhat surprises me, since we pull a lot -- including all the exponentials -- out of the loop). I wonder whether it is not worth switching this on by default after all. We are happily rewriting expressions ourselves, pulling out constants and so on -- I think the inaccuracy introduced by `-ffast-math` is negligible compared to that.
> [MRG] Use homogeneous delays if possible

- brian2/codegen/codeobject.py
- brian2/codegen/runtime/cython_rt/templates/synapses_create.pyx
- brian2/codegen/runtime/cython_rt/templates/synapses_create_array.pyx
- brian2/codegen/runtime/numpy_rt/templates/synapses_create.py_
- brian2/codegen/runtime/numpy_rt/templates/synapses_create_array.py_
- brian2/codegen/runtime/weave_rt/templates/synapses_create.cpp
- brian2/codegen/runtime/weave_rt/templates/synapses_create_array.cpp
- brian2/devices/cpp_standalone/templates/synapses_create.cpp
- brian2/devices/cpp_standalone/templates/synapses_create_array.cpp
- brian2/equations/equations.py
- brian2/synapses/spikequeue.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- brian2/utils/arrays.py
- docs_sphinx/user/synapses.rst
I realized that we never implemented supported for expressions referring to the index of the synapse, i.e. after you create multiple synapses:
```
syn.connect(True, n=2)
```
There was no way to e.g. set weights or delays differently for the first and the second synapse connecting `i` and `j` (with the exception that in run time mode you could use `syn.w[:, :, 0] = ...`). I just needed this myself so I implemented it. This is basically done and working but I have a few  questions before merging it:
* What should be the name of this attribute? In early drafts I think we proposed `k` (following `i` and `j`) but I have the feeling that the chance for clashes with user variables is too high, especially given that `k` in the sense of the synapse index will rarely be used. In the code I …
> [MRG] Store the "synapse number" of each synapse

- .travis.yml
- appveyor.yml
- brian2/__init__.py
- brian2/codegen/cpp_prefs.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/makefile
- dev/conda-recipe/meta.yaml
- docs_sphinx/user/computation.rst
- setup.py
I just enabled the fast compilation options in this branch, testing on Linux did not show any test failures but we don't yet have the results from appveyor. If there's no problem, then it seems we do not actually have to change anything (apart from the documentation). I included an auto-detection of the arch flag for Windows in the same way it was done in standalone when you specified `native=True`. This makes the latter obsolete, do you think this is important enough to have as a specific keyword argument to build instead of having it set simply via the compiler options? I think users will build for their own machine in 99% of the cases and if not, they probably have to set some compiler/linker settings anyway, no?
> [MRG] Use compiler settings for maximal speed by default

- brian2/codegen/codeobject.py
- brian2/codegen/generators/base.py
- brian2/codegen/translation.py
- brian2/core/base.py
- brian2/core/network.py
- brian2/core/variables.py
- brian2/devices/cpp_standalone/device.py
- brian2/equations/unitcheck.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/input/poissoninput.py
- brian2/input/spikegeneratorgroup.py
- brian2/spatialneuron/spatialneuron.py
- brian2/stateupdaters/base.py
- brian2/stateupdaters/exact.py
- brian2/stateupdaters/explicit.py
- brian2/stateupdaters/exponential_euler.py
- brian2/synapses/synapses.py
- brian2/tests/test_namespaces.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_parsing.py
- brian2/tests/test_refractory.py
- brian2/tests/test_stateupdaters.py
- docs_sphinx/developer/equations_namespaces.rst
As we discussed, instead of implementing joblib caching (#124) I first had a look at where the preparation time is spend. In this branch, I implemented a few small uncontroversial changes (e.g. `check_code_units` was called before `create_runner_codeobj`, but the latter called `check_code_units` again), but also some bigger changes that are at least worth discussing:
1. Instead of passing down the level argument down from `before_run` all the way until when namespaces are actually resolved, we get the local namespace in the `run` method and pass this namespace down. The advantage is that we don't have to get the local namespace several times, which is relatively expensive since we have to go through a lot of objects and call `isinstance` on them to see whether we are interested in them. …
> [MRG] Faster `before_run`

- brian2/core/namespace.py
- brian2/groups/group.py
- brian2/tests/test_functions.py
I mentioned this in #593 but forgot to actually change this. We are currently checking all of the objects in the local namespace for their type, and only include the objects we are generally interested in (numbers, functions, ...) in the namespace dictionary that we pass on. This is quite expensive, since the full local namespace can be big. With the small change here, we instead pass the full local namespace down to the resolve method and only do the type checks for names we are actually interested in.
This reduces the time that `before_run` takes by a very small amount for e.g. the CUBA example, but it can have a significant effect for scripts that make a use of string expressions a lot.
> [MRG] Don't check all objects in the local namespace for their type

- brian2/codegen/codeobject.py
- brian2/codegen/generators/base.py
- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/codegen/runtime/numpy_rt/templates/spikemonitor.py_
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/codegen/templates.py
- brian2/core/clocks.py
- brian2/core/functions.py
- brian2/core/network.py
- brian2/devices/cpp_standalone/codeobject.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/stateupdaters/exact.py
- brian2/tests/test_clocks.py
- brian2/tests/test_functions.py
- brian2/tests/test_monitor.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_templates/__init__.py
- brian2/units/fundamentalunits.py
Ok, this one deserves slightly more discussion. It fixes a few "low-hanging fruits" for performance, hopefully it should now compare better against Brian 1. Nothing too controversial here, the changes are:
* As mentioned previously, the way the clock was accessed in `Network.run` was far from optimal. I changed it in a way that takes some logic out of the `Clock` class and puts direct access to the variables in `Network.run`. This makes the code somewhat less readable but I think it is justified here since `Clock.running` and `Clock.tick` were only ever used from within the runtime `Network.run` function, standalone had to do something else. So not having this in `Clock` but instead in `Network.run` seems like the sensible choice, instead of having very runtime specific code in the …
> [MRG] Fix various inefficiencies

- brian2/devices/cpp_standalone/device.py
- brian2/devices/device.py
- brian2/tests/__init__.py
- brian2/tests/features/base.py
- brian2/tests/test_complex_examples.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_devices.py
- brian2/tests/test_functions.py
- brian2/tests/test_monitor.py
- brian2/tests/test_network.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_poissongroup.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spatialneuron.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_stateupdaters.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_synapses.py
- brian2/tests/test_thresholder.py
- brian2/tests/test_timedarray.py
- docs_sphinx/user/devices.rst
This fixes #512: `set_device` now has a `build_on_run` argument which defaults to `True` and the overwritten `network_run` function in the standalone device now calls `build` directly if it has not been set to `False`. For quite a few scripts, this now means that a single `set_device('cpp_standalone')` line is enough to switch to the standalone device. All other arguments that `set_device` gets will be stored in `Device.build_options` and will be propagated to `Device.build` when it is automatically called (so you can do something like `set_device('cpp_standalone', directory='my_dir', debug=True)`.
For testing, this also means that the `standalone-compatible` tests now no longer use a "simple" device (`CPPStandaloneSimpleDevice` does not exist anymore), but instead use this mechanism. For …
> [MRG] Build devices by default at the first `run` call

- brian2/codegen/generators/cython_generator.py
For some reason this code wasn't working, but we never actually use floats anywhere so for the moment it's fine to just have doubles I think.
Tiny change ready to merge as soon as tests pass I think.
> [MRG] Make clip not use fused types (fixes #609)

- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
Changed it so that by default it uses the same cache directory that Cython's inline uses, but you can override with your own preference.
> [MRG] Customise Cython cache dir (fixes #599)

- brian2/parsing/sympytools.py
As noted by Kees de Leeuw on the mailing list, our test suite fails with sympy 0.7.7 (not released yet). This is because the default sympy printing changed, equalities will be printed as `Eq(a, b)` instead of `a == b` -- this commit manually overrides this behaviour in our own custom printer (we already do a similar thing to have `a and b` instead of `And(a, b)`).
> [MRG] Fix problem with sympy 0.7.7 

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_functions.py
- examples/standalone/STDP_standalone.py
- examples/standalone/cuba_openmp.py
The reason the standalone examples were failing was that they used the new `build_on_run` mechanism (which we switched on by default) as well as an explicit `device.build` call. I fixed this (also in one test) and made `CPPStandaloneDevice.build` raise an error for this situation (which can occur when copying older examples or upgrading code to the new version) -- this should make it *much* clearer what the actual problem is.
> [MRG] Standalone error for manual build with `build_on_run`

- brian2/sphinxext/generate_examples.py
- examples/COBAHH.py
- examples/frompapers/Clopath_et_al_2010_homeostasis.py
- examples/frompapers/Clopath_et_al_2010_no_homeostasis.py
This adds the Clopath et al. 2010 example contributed by Jacopo Bono. It also fixes small issues with encodings (you can now use "ö" etc. in the doc string) and allows for more than one comment line in the beginning of the example file.
I slightly changed one of Jacopo's example to use a `run_regularly` operation instead of a loop over runs, but I left the nested loop for the second example in place. Replacing this with a single run is certainly feasible, but it does not take a crazily long time as it is, so I think it is not really urgent and might make the code harder to read.
Ready to merge from my side.
> [WIP] Plasticity example

- dev/tools/run_examples.py
- examples/adaptive_threshold.py
- examples/advanced/stochastic_odes.py
- examples/compartmental/cylinder.py
- examples/compartmental/hh_with_spikes.py
- examples/compartmental/hodgkin_huxley_1952.py
- examples/compartmental/infinite_cable.py
- examples/compartmental/morphotest.py
- examples/frompapers/Brette_2012/Fig1.py
- examples/frompapers/Brette_2012/Fig3AB.py
- examples/frompapers/Brette_2012/Fig3CF.py
- examples/frompapers/Brette_2012/Fig4.py
- examples/frompapers/Brette_2012/Fig5A.py
- examples/frompapers/Brette_2012/params.py
- examples/frompapers/Clopath_et_al_2010_no_homeostasis.py
- examples/frompapers/Sturzl_et_al_2000.py
- examples/frompapers/kremer_et_al_2011_barrel_cortex.py
- examples/synapses/jeffress.py
Not much to review here, I just noticed that the `run_examples` script did not work under Python 3, and the same was true for a few individual examples. Since Python 3 is becoming more popular now and we never said that the examples should be run with Python 2, this needed fixing.
> [MRG] Make examples run under Python3

- brian2/codegen/runtime/numpy_rt/templates/group_variable_set_conditional.py_
- brian2/tests/test_neurongroup.py
Functions like `rand()` only look at the length of the array to know how many numbers they should produce.
Fixes #624
> [MRG] Use an integer index array instead of a  boolean array in the `group_variable_set_conditional` numpy template

- brian2/codegen/translation.py
- brian2/equations/codestrings.py
- brian2/equations/equations.py
- brian2/groups/neurongroup.py
- brian2/parsing/sympytools.py
- brian2/spatialneuron/spatialneuron.py
- brian2/stateupdaters/exact.py
- brian2/stateupdaters/explicit.py
- brian2/stateupdaters/exponential_euler.py
- brian2/tests/test_functions.py
It is less elegant than I'd like it to be but to make sure we catch this problem everywhere where we use sympy, I had to include it in `str_to_sympy` and change this function so that it optionally takes a `variables` dictionary (so it knows which functions are stateful). In a way this makes perfect sense because an abstract code block should always be accompanied by a `variables` dictionary, otherwise it is not meaningful. There are still a few places where the function is used without this argument, though, but those are about printing (using `str_to_sympy` to then use sympy's pretty printing facilities), for parsing state updater descriptions or in one somewhat ugly case, to just find out whether there are implicitly vectorized functions (i.e. `func()` calls) in an expression.
One …
> [MRG] Raise error for multiple stateless functions call in an expression

- brian2/codegen/runtime/cython_rt/templates/spatialneuron_prepare.pyx
- brian2/codegen/runtime/cython_rt/templates/spatialstateupdate.pyx
- brian2/codegen/runtime/numpy_rt/templates/spatialneuron_prepare.py_
- brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
- brian2/codegen/runtime/weave_rt/templates/spatialneuron_prepare.cpp
- brian2/codegen/runtime/weave_rt/templates/spatialstateupdate.cpp
- brian2/core/variables.py
- brian2/devices/cpp_standalone/templates/spatialneuron_prepare.cpp
- brian2/devices/cpp_standalone/templates/spatialstateupdate.cpp
- brian2/spatialneuron/spatialneuron.py
Not a particularly interesting pull request... Renames all the internal variables used in the `spatialstateupdate` template so that they start with `_`. Also pulls them out of the `SpatialNeuron` equations (they are nothing the user cares about). To make this easier, introduces a new `add_arrays` method that allows to add several `ArrayVariable` objects at once.
> [MRG] Rename SpatialNeuron variables

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
In general, we do not care much about the performance of `Quantity` operations, since they are not used during the actual simulation. However, the `Morphology` object does use them, and constructing/analyzing/plotting such objects can therefore benefit from performance improvements. This PR includes a few optimisations, most of them are just different ways of doing the same thing (e.g. replacing an `isinstance` test by a try/except), if I am not mistaken there's only one semantical difference: previously, calling `Quantity` with an existing quantity *and* a dimension argument would raise an error if the two were inconsistent (e.g. `Quantity(3*mV, dim=second.dim)`). Now, this will just force the dimension given as the `dim` argument. Raising an error does make more sense, I think, but I …
> [MRG] Unit performance improvements

- brian2/core/variables.py
- brian2/equations/unitcheck.py
- brian2/tests/test_synapses.py
In addition, make the `Variable` constructor handle `Quantity` objects as well.
Change one test for the summed variable mechanism to expose this error.
Fixes #674
> [MRG] Provide an actual `Unit` (and not a `Quantity`) for the `Variable` object in `check_units_statements`

- brian2/core/network.py
- brian2/tests/test_network.py
- docs_sphinx/introduction/release_notes.rst
Fixes #681 
As a side note: I added a commit that mentions the bug (and the users that reported it) already in the next release notes. I think it is a good idea that PRs that introduce a major new feature or fix important bugs do that as part of the PR, that way we'll have less work at release time and it is less likely that we forget something.
> [MRG] Do not alter the stored state of a network when restoring it

- brian2/equations/codestrings.py
- brian2/stateupdaters/explicit.py
- brian2/tests/test_codestrings.py
- brian2/tests/test_stateupdaters.py
- docs_sphinx/introduction/release_notes.rst
Fixes #686 
There were two issues that together led to the bug:
1. The explicit state updater code does not apply the stochastic part `g(x,t) * dW` of a state updater description to an expression if that expression does not have a `...*xi` term. This is fine, the problem is that the same logic was applied to the *non-stochastic* part, but that part is (e.g. for Euler) `x + dt*f(x, t)`, i.e. even if there is no `f(x, t)` in the expression, it should still include the `x`.
2. The above approach was present in the code for a long time but it did not lead to any issue because our code to split an expression into stochastic and non-stochastic part did return `0.0` (and not `None`) for an empty non-stochastic part, meaning that the non-stochastic part of the state updater description was …
> [MRG] Fix the handling of empty non-stochastic parts in equations

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/network.cpp
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/synapses/synapses.py
- brian2/tests/test_neurongroup.py
This is a small optimization but something that bothered me for a while. With this PR, groups that do not need a state updater (say `G = NeuronGroup(10, 'v:1')` ) will:
* no longer search for and apply an integration algorithm (i.e. no INFO message either)
* no longer generate "do-nothing" state update code that will be executed at every time step
> [MRG] Avoid empty state updaters

- brian2/input/poissongroup.py
- brian2/tests/test_poissongroup.py
- docs_sphinx/introduction/release_notes.rst
- docs_sphinx/user/input.rst
Following our discussion at #660 I did not add any warning or additional mechanism to use the previous behaviour (but I adapted the documentation).
Closes #660
> [MRG] Interpret string expressions for the `rates` argument of `PoissonGroup` at every timestep

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_network.py
- docs_sphinx/introduction/release_notes.rst
As discussed in #695, using the "str" instead of "repr" representation of the floating point value of the total runtime led to a one-timestep difference under certain (quite specific) circumstances. This should be fixed with this PR.
Fixes #695
> [MRG] Do not lose precision when inserting floating point values into standalone code

- brian2/codegen/runtime/weave_rt/templates/synapses.cpp
- brian2/units/fundamentalunits.py
- docs_sphinx/introduction/release_notes.rst
As reported in this [mailing list thread](https://groups.google.com/d/topic/brian-development/CK76RuDHRbg/discussion), there is a memory leak in Brian 2.0rc1. It turned out that there were actually two issues: unit objects were unnecessarily stored over an over again in the unit registry (this is what you see in the output from the `pympler` module). However, this was only a minor memory leak (and one that existed, albeit less severe, in earlier versions). The main memory leak was in the spike propagation template for weave, where we received a reference to a numpy array from the spike queue and did not `PY_DECREF` it in the end. This memory leak would not matter in most use cases, but by using a loop over runs and storing/restoring the network, many spike queues were generated and the …
> [MRG] Improve memory usage

- brian2/devices/cpp_standalone/templates/network.cpp
I think the general idea of `make_pair` is that it infers its types automatically from the arguments (otherwise you would create the pair explicitly with `std::pair<T1, T2>`). Apparently leaving away the types works on gcc and msvc, while having them does not work with gcc 6 (in its default C++14 mode).
Fixes #701
> [MRG] Use `std::make_pair` without template types

- brian2/codegen/codeobject.py
- brian2/core/namespace.py
- brian2/core/variables.py
- brian2/devices/cpp_standalone/device.py
- brian2/equations/equations.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/parsing/sympytools.py
- brian2/synapses/synapses.py
- brian2/tests/test_equations.py
- brian2/tests/test_namespaces.py
While looking into #699 I noticed that the code in 2.0rc1 not only had a memory leak but was also running somewhat slower than in 2.0b4. The test code was certainly a bit extreme (very short run repeated many times), but similar use cases are common. While profiling I noticed that the namespace resolution took a lot of time, because we'll ask for the stack frame again and again, whenever we resolve names in code (even if we resolve the names with internal names, we still check for name clashes with external names to issue a warning). This pull request changes this and gets the local namespace once at the earliest point of time (most importantly in `run()`, but also when setting a variable with a string expression or when connecting synapses). The namespace dictionary is then passed down …
> [MRG] Faster before run

- brian2/codegen/codeobject.py
- brian2/codegen/optimisation.py
- brian2/core/variables.py
- brian2/parsing/bast.py
- brian2/synapses/synapses.py
- brian2/tests/test_refractory.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/release_notes.rst
This PR collects fixes for a few issues that were discovered in the context of synaptic pathways (in recent mails to the mailing list):
* nested subexpressions led synaptic pathways to fail because of some unnecessarily complicated attempts to link to them (references to subexpressions are a bit tricky in general because they refer to other variables in the source group, not in the group where they are linked from -- this means we cannot simply use the subexpression literally).
* not related to the synaptic pathway, but it manifested for a user on the mailing list in this context: our conditional write mechanism is a bit fragile, since we include the conditional write variable (i.e. `not_refractory` for `v`) under this name in the variables dictionary. This can clash with an already …
> [MRG] Fix pathway variables and other small issues

- brian2/__init__.py
- brian2/tests/__init__.py
- brian2/utils/logger.py
- docs_sphinx/advanced/index.rst
- docs_sphinx/advanced/logging.rst
- docs_sphinx/developer/guidelines/logging.rst
- docs_sphinx/user/models.rst
This fixes/improves the issues mentioned in #692 and #691. Most importantly, changing the logging preferences via a file now works (previously, the logging system was initialized before preferences files were loaded). Additional changes:
* new preference to switch off writing stdout/stderr to a file `logging.std_redirection_to_file`
* the stdout/stderr filenames are prefixed with `brian_stdout`/`brian_stderr` to be more consistent with `brian_debug...` and `brian_script...`
* The documentation of the logging system is now split into a part for users and a part for developers, I also added a warning about setting basic logging preferences (which only works via a file, not in the script itself)
> [MRG] Logger improvements

- brian2/codegen/runtime/cython_rt/templates/synapses_create_generator.pyx
- brian2/codegen/runtime/numpy_rt/templates/synapses_create_generator.py_
- brian2/codegen/runtime/weave_rt/templates/synapses_create_generator.cpp
- brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
I realized that our changes to synapse creation did actually break the "synapse-to-synapse" connections we need for the astrocytes project. We had a test for that, but that test used 1-to-1 connections everywhere so the use of incorrect indices went unnoticed. The change is to not rely on the pre-defined arrays of `arange(N)` that every `NeuronGroup` has but instead create them on the fly -- performance-wise it should not change anything (addition of two variables instead of an array lookup), except maybe for numpy (because we now do an explicit check instead of relying on an automatic `IndexError` -- however, this has the advantage that the error message is now clearer and consistent with weave/cython). I did not notice anything significant in some quick testing.
The names `all_pre` and …
> [MRG] Synapse to synapse fix

- brian2/input/spikegeneratorgroup.py
I don't know if I'm being very naive here and I'm missing something; but whenever and however I use SpikeGeneratorGroup, it returns an DimensionsMismatchError.
The code imposes "period" to be a quantity in seconds. However, np.max(times) outputs a unitless quantity (numpy converts everything to numpy.array), so brian itself complains it cannot compare them.
I couldn't find any workaround at all, except changing the code.
Am I missing something?
Thanks!
> SpikeGeneratorGroup: period and np.max(times) comparison error

- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/parsing/expressions.py
- brian2/parsing/rendering.py
- brian2/tests/test_numpy_codegen.py
- brian2/tests/test_parsing.py
- brian2/tests/test_timedarray.py
This fixes some less than useful error messages that I had on my list for quite a while, see explanations in the commit logs. The only somewhat debatable change is the fix for #646 -- the `exec` used to execute numpy code objects is now wrapped in `try/exec` and will give the actual code line that raised the error. This comes at the cost of a slightly slower code execution, in one example (in some very unsystematic benchmarking) I saw a runtime increase of 10%. I still think this is worth doing, numpy would somewhat become the "debug device". If you see for example a segmentation fault when running your simulation, it is very much possible that switching to numpy will give us a helpful error message (e.g. an `IndexError` when we go beyond array bounds). I actually did this change a few …
> [MRG] Error message improvements

- .travis.yml
- appveyor.yml
- brian2/__init__.py
- brian2/devices/cpp_standalone/device.py
- dev/conda-recipe/bld.bat
- dev/conda-recipe/build.sh
- dev/conda-recipe/meta.yaml
- docs_sphinx/introduction/install.rst
- docs_sphinx/introduction/known_issues.rst
This removes the workarounds for MSVC that are no longer necessary: VS 2015 works fine with OpenMP now and numpy 0.10.2 fixed the `compiler_cxx` issue.
I also updated the installation instructions for code generation on Windows with Python 3.5. Unfortunately we still need a manual installation of compilers, the runtime environment that I mentioned in issue #591 does not include the compilers.
I also changed a small thing in the appveyor builds: conda packages are now only built for pull requests or on the master branch, that makes the tests slightly faster in development branches (and the conda builds do sometimes fail anyway just because of server issues).
It *seems* that the issue reported in #724 has fixed itself, but let's wait for the tests to run through.
> [MRG] Remove MSVC workarounds

- brian2/monitors/spikemonitor.py
- brian2/tests/test_monitor.py
See discussion in #725.
Fixes #725
> [MRG] Use a stable sort algorithm so that `Spikemonitor.spike_train` returns sorted spike trains

- brian2/core/variables.py
- brian2/groups/group.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/release_notes.rst
- docs_sphinx/user/synapses.rst
This implements the error messages as dicussed in #737 -- you get an error when you write to a synaptic variable without a preceding `connect` or when you include a `Synapses` object without a `connect` in a simulation and run it.
I realized that a warning for a `connect` that results in 0 synapses is actually not that trivial to implement. The synapse creation is done in the template and on the Python level, we do not know about the number of synapses created. We could make a change to the templates so that they return the number of created synapses but this might be a bit of a waste since we probably want to change this again when we implement #263. Also, we need to deal with standalone (same for the simple solution where we check the number of synapses before and after the synapse …
> [MRG] Error for missing connect call

- brian2/sphinxext/generate_examples.py
- dev/tools/docs/build_tutorials.py
- docs_sphinx/index.rst
- docs_sphinx/introduction/index.rst
- docs_sphinx/introduction/overview.rst
- tutorials/1-intro-to-brian-neurons.ipynb
- tutorials/2-intro-to-brian-synapses.ipynb
This currently works, but there are a few things I'd like to add. Essentially, here we have a few links added to ``bdevans/brian-binder`` via ``mybinder.org``. There are some additional tools in that repo.
Still to do:
To do in Brian repo:
To do in ``brian2-binder`` repo:
@bdevans
> [MRG] Use Binder service for tutorials and examples

- brian2/spatialneuron/morphology.py
- docs_sphinx/introduction/release_notes.rst
This fixes certain inefficiencies in the `Morphology` class. Coordinates are now internally stored without units (you can access the unitless coordinates using names with a trailing underscore) and a lot of unnecessary evaluations of (calculated) coordinates are removed. 
Plotting the morphology mentioned in brian-team/brian2tools#13 now takes 0.5s in 2D and 3.5s in 3D on my machine -- there's still room for improvement (also on the `brian2tools` side), but this is much better than "forever" :)
Closes #741
> [MRG] Improve morphology performance

- brian2/core/functions.py
- brian2/groups/group.py
- brian2/parsing/expressions.py
- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
It's a bit of a messy addition (we should do a bit of refactoring at some point, `parse_expression_unit` and `is_boolean_expression` could potentially be merged, treating "boolean" as a special unit as we do in other places), but I stumbled across this missing feature when documenting how to translate Brian 1's custom thresholds (defined by functions) to Brian 2. This was very cumbersome before this change since you could not define a boolean-returning function that actually gets recognized as such by the parsing system.
> [MRG] Support user-defined functions with boolean argument/return value

- brian2/equations/equations.py
- brian2/spatialneuron/spatialneuron.py
- brian2/tests/test_spatialneuron.py
- docs_sphinx/introduction/release_notes.rst
This fixes #743, where `SpatialNeuron` did not detect a non-linear dependency on ``v`` when it was "hidden" in a point current. The code in `SpatialNeuron.__init__` is far from optimal, it mixes creating new equations from `SingleEquation` objects and from strings, this should be rewritten at some point... Still, this fixes the bug for now. I also enabled the `(constant over dt)`  flag for `SpatialNeuron`. This is quite important, since it is possible that some users cannot run their models with `SpatialNeuron` anymore now that it correctly detects a non-linearity in their equations. By marking the non-linear part as "constant over dt", everything should work again.
> [MRG] Correct linear dependency check in SpatialNeuron

- brian2/codegen/codeobject.py
- brian2/codegen/cpp_prefs.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/tests/test_parsing.py
It's a small refactoring change, but we were duplicating some code to enable 64bit->32bit cross-compilation in several places. It also turns out that getting the platform information is somewhat costly (at least on my machine) -- it's only a couple of milliseconds but in the previous code it was asking for this information again and again for each `CodeObject` creation. In a small test with a simulation that included many short `run` statements in a loop (far from optimal with current Brian 2...), this made actually a significant performance difference!
> [MRG] Small refactoring to only ask for the platform information once

- brian2/input/spikegeneratorgroup.py
This avoids that it is indexed with the default index and therefore with the size of the group (which is the number of "neurons", not spikes)
Fixes #752
> [MRG] Define `spike_number` as its own index in `SpikeGeneratorGroup`

- .travis.yml
- brian2/codegen/cpp_prefs.py
- brian2/core/network.py
- brian2/core/variables.py
- brian2/devices/cpp_standalone/device.py
- brian2/groups/group.py
- brian2/parsing/expressions.py
- brian2/tests/test_stateupdaters.py
This isn't quite ready yet, but the basic ideas are there. Would be interested if you took a look and gave me some feedback @mstimberg.
The first thing is that by changing the default compiler options for MSVC we avoid the problem reported in #626 (see discussion there).
The next thing is that after a run, or on loading a state variable from disk, we check for nans or large values and warn if we find any. Currently, this isn't passing tests because it keeps raising the following error:
```
ERROR: brian2.tests.test_stateupdaters.test_refractory_stochastic
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\Anaconda\lib\site-packages\nose\case.py", line 197, in runTest
self.test(*self.arg)
File …
```
> [MRG] Warn about unstable integration

- brian2/groups/neurongroup.py
- brian2/tests/test_refractory.py
It turned out #764 was a regression, the `KeyError` was raised before the warning we already had in place. This commit fixes this and adds a test for the presence of the warning.
A general remark: I activated the new "review required" feature that github introduced recently. Instead of just commenting and saying "good to merge", we can now do an official review and set the status -- let's see how this goes!
Not relevant for the current PR:= but github also has a new nice "rebase and merge" feature, we should try this when a branch got outdated by other merges, this should make our development history easier to follow.
> [MRG] Re-enable the warning about a missing `refractory` argument

- brian2/codegen/cpp_prefs.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/devices/cpp_standalone/device.py
This is necessary for linking with C libraries installed via anaconda
It shouldn't hurt when not using anaconda (at least from the Linux perspective): `sys.prefix` for the standard system Python is `/usr`, which means that we'd add `/usr/include` and `/usr/lib` to the include/library paths -- but they are checked by default, anyway.
> [MRG] Add sys.prefix/lib to the library dir in C++ compilation

- brian2/input/poissongroup.py
- brian2/tests/test_poissongroup.py
- docs_sphinx/introduction/release_notes.rst
- docs_sphinx/user/input.rst
After merging #770 I noticed that the example code in the documentation is actually slightly wrong:
```Python
stimulus = TimedArray(np.tile([100., 0.], 5), dt=100.*ms)
P = PoissonGroup(1, rates='stimulus(t)')
```
The `TimedArray` is dimensionless, `stimulus(t)` therefore needs to be multiplied by `Hz` before using it as a rate.
With this PR, the above code now raises a `DimensionMismatchError`.
> [MRG] Check units in PoissonGroup rates defined by strings

- brian2/codegen/runtime/cython_rt/templates/ratemonitor.pyx
- brian2/codegen/runtime/weave_rt/templates/ratemonitor.cpp
- brian2/devices/cpp_standalone/templates/ratemonitor.cpp
- brian2/tests/test_monitor.py
- docs_sphinx/introduction/release_notes.rst
See #772 for details about this bug.
I think we should put this fix out there rather sooner than later. How about doing a 2.0.1 (probably better than 2.1 if there is no new feature, right?) release in a few days?
> Fix `PopulationRateMonitor` for subgroups

- brian2/codegen/runtime/numpy_rt/templates/spikemonitor.py_
- brian2/codegen/runtime/weave_rt/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
- brian2/tests/test_monitor.py
- docs_sphinx/introduction/release_notes.rst
Here's the fix for #777, see the issue for more details.
In addition to the bug fix this PR includes two micro optimisations (one for numpy, one for C++ standalone) for better `SpikeMonitor` performance when it does not record from a subgroup. The optimisation for C++ standalone is simply a copy of the improved algorithm in weave (without the bug of course ;-) ).
> [MRG] Spikemonitor subgroup fix

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_network.py
- docs_sphinx/introduction/known_issues.rst
- docs_sphinx/introduction/release_notes.rst
This was more an annoyance than a serious bug, but for users it was very hard to figure out what went wrong. If you wrote the following code in standalone mode:
```Python
run(some_time, report='text')
run(some_time)
```
you'd get a compilation error. The reason was that the standalone device stored the reporting function to use in its `report_function` attribute, and that was overwritten with the second run call.
Now in principle we could support multiple report functions (e.g. `CPPStandaloneDevice.report_function` could be a list), but I did not want to bother complicating the code for that rather unimportant use case. What is allowed now is code like the above, i.e. some runs with a report function and some without, but using different report function (e.g. `report='stdout'` and …
> [MRG] Standalone multiple runs report fix

- brian2/codegen/cpp_prefs.py
- brian2/devices/cpp_standalone/device.py
- dev/continuous-integration/run_test_suite.py
I was a bit annoyed with the standalone compilation taking so much time and it turned out that just using `make` with parallel jobs reduced the time drastically (at least on Linux). I added two new preferences for arguments to the `make`/`nmake` commands, and added `-j` for Linux by default. I also enabled parallel compilation for Windows, but this does not seem to have much of an effect (at least on our test server).
I think we could also drastically improve Cython runtime compilation, but this requires refactoring the code a bit (the `compile` step would trigger compilation in a separate process, a result would only be required when we reach `run`. This is a longer term project (and then, we might reconsider our codegen targets anyway), so let's not worry about that for now.
> [MRG] Parallel compile

- brian2/core/variables.py
- brian2/devices/cpp_standalone/templates/group_variable_set.cpp
- brian2/tests/__init__.py
- brian2/tests/test_base.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_functions.py
- brian2/tests/test_monitor.py
- brian2/tests/test_network.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_synapses.py
- docs_sphinx/developer/guidelines/testing.rst
This adds features to our test suite to allow easier testing for devices not shipped as part of Brian 2. The two main changes are:
* `brian2.test` has a new argument to provide additional directories with tests to execute
* Tests with more than one run statement can be marked as `standalone-compatible` as well, they need an additional `multiple-runs` flag and an explicit `device.build` call (which will be ignored for runtime devices).
All of this is documented in the testing guidelines. Fixes #789
> [MRG] More general tests

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
> [MRG] Recurse into subexpressions when getting identifiers from a synaptic condition

- brian2/synapses/synapses.py
- docs_sphinx/introduction/release_notes.rst
> [MRG] Use `linear` instead of `independent` state updater (`event-driven` equations)

- brian2/devices/cpp_standalone/templates/network.cpp
- docs_sphinx/introduction/release_notes.rst
> [MRG] Floating point instead of integer division (elapsed time for report function)

- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/tests/test_functions.py
Issue: #782
This pull request makes a more abstract version of the `_clip` function
to accommodate also for arguments of other types than `double`.
It would probably be a good idea to add test cases for each of the different
types, but I have not really looked into the internals of your test suite yet.
> Implement generic typing for `_clip`

- brian2/devices/cpp_standalone/device.py
- docs_sphinx/introduction/known_issues.rst
- docs_sphinx/introduction/release_notes.rst
This fixes #803 by introducing a new preference for environment variables that will be set during the execution of standalone simulations which defaults to `LD_BIND_NOW=1`. I did not bother introducing different preferences for Windows and *nix, I don't think having a non-relevant environment variable (such as `LD_BIND_NOW` on Windows) should hurt.
> [MRG] Workaround glibc bug

- brian2/codegen/generators/cpp_generator.py
- brian2/core/clocks.py
- brian2/devices/cpp_standalone/brianlib/clocks.h
- brian2/devices/cpp_standalone/templates/synapses_classes.cpp
- brian2/synapses/cspikequeue.cpp
- brian2/synapses/cythonspikequeue.pyx
- dev/conda-recipe/meta.yaml
In current master, we generate a whopping 169 variants of `brian_mod`, even though you cannot generate variables (or number literals) with data types such as `unsigned int` or `short` at the moment. This clutters the generated code quite a bit (#594 would of course deal with this as well) without a clear gain. This PR is still quite generous by allowing for six data types (i.e. a total of 36 variants), but we probably rather want to err on the side of caution here.
> [MRG] Reduce the number of supported data types for `brian_mod`

- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/codegen/runtime/numpy_rt/templates/group_get_indices.py_
- brian2/codegen/runtime/numpy_rt/templates/group_variable_get_conditional.py_
- brian2/codegen/runtime/numpy_rt/templates/group_variable_set.py_
- brian2/codegen/runtime/numpy_rt/templates/group_variable_set_conditional.py_
- brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
- brian2/codegen/runtime/numpy_rt/templates/spikemonitor.py_
- brian2/codegen/runtime/numpy_rt/templates/stateupdate.py_
- brian2/codegen/runtime/numpy_rt/templates/summed_variable.py_
- brian2/codegen/runtime/numpy_rt/templates/threshold.py_
- brian2/tests/__init__.py
- brian2/tests/test_monitor.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_synapses.py
Previously, the `_vectorisation_idx` variable in numpy templates was allowed to be a scalar variable which would *directly* be interpreted as the number of values that e.g. `rand()` should produce, or a vector whose *length* would determine the number of values. In addition, `rand()` would return a scalar value if the `_vectorisation_idx` had the value 1 or was of length 1, and an array otherwise.
This was a bit of mess, I now made this (hopefully) a bit clearer:
* `rand()` will return a scalar value if it receives a scalar value (remember, in the long run, we want to use `_vectorisation_idx` to get reproducible random numbers, so we might need the freedom to have different values for `_vectorisation_idx`, even though we do not need to determine how many numbers to produce.)
* If `rand()` …
> [MRG] Fix `_vectorisation_idx` for numpy target

- docs_sphinx/developer/units.rst
Just to show I am comfortable using Git. 
Some of the methods mentioned in the "List of methods" and "Math operations" section could not be read as they were enclosed in single quotations(``...``) and hence occupied a single line. So I broke them up into groups of 90-100 characters and enclosed each group in different quotations.
> Minor changes to the documentation

- brian2/core/namespace.py
- brian2/equations/equations.py
- brian2/units/fundamentalunits.py
Just a small follow-up to the unit-related changes in #821: I noticed that the display for unknown units was not optimal:
```pycon
>>> Equations('dv/dt = -v/tau : volta')
...
EquationError: Error parsing the unit specification for variable "v": Unit specification refers to "volta", but
this is not a base unit. The following base units are allowed: ampere, coulomb, farad, henry, hertz,
joule, katal, kelvin, kgram, klitre, lumen, lux, metre, mmolar, mole, newton, ohm, pascal, radian, second,
siemens, sievert, tesla, volt, watt, weber (plus some variants of these, e.g. "Hz" instead of "hertz", or
"meter" instead of "metre").
```
This error message uses some non-standard forms ("ampere", "kgram") and the "plus some variants" bit is maybe a bit vague. With this PR we'd get:
```pycon
>>> …
```
> [MRG] Use the standard names in error messages for unknown units

- brian2/groups/neurongroup.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- examples/frompapers/Vogels_et_al_2011.py
As discussed in #818: raise an error if a user calls their variables "..._pre" or "..._post", to avoid confusion with the `_pre`/`_post` suffix in synapses.
> [MRG] Forbid "..._pre"/"..._post" variable names

- brian2/codegen/runtime/cython_rt/templates/spikemonitor.pyx
- brian2/codegen/runtime/cython_rt/templates/statemonitor.pyx
- brian2/codegen/runtime/weave_rt/templates/spikemonitor.cpp
- brian2/codegen/runtime/weave_rt/templates/statemonitor.cpp
- brian2/codegen/templates.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/devices/cpp_standalone/templates/group_variable_set_conditional.cpp
- brian2/devices/cpp_standalone/templates/main.cpp
- brian2/devices/cpp_standalone/templates/makefile
- brian2/devices/cpp_standalone/templates/objects.cpp
- brian2/devices/cpp_standalone/templates/run.cpp
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/synapses.cpp
- brian2/devices/cpp_standalone/templates/synapses_create_array.cpp
- brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp
- brian2/devices/cpp_standalone/templates/win_makefile
- docs_sphinx/introduction/release_notes.rst
On Linux, standalone's `main` file was always re-compilated, since it was not mentioned by name (instead there was an `executable` target). Also, the ordering of arrays in `object.cpp` was not completely deterministic: it was sorted by "name", but this was just the name of the variable (e.g. many variables have the name "i"). I changed all this, and also changed the default for `clean` to `False`. I am not 100% about this one, because it can actually lead to compilation errors if you re-run the same simulation but change compilation parameters (or activate OpenMP). I mention this in the error message now. Either way, I'm not seeing any recompilation if I run the same script twice.
So, should stay with `clean=True` by default for safety or switch to `clean=False`? I rarely have compilation …
> [MRG] Avoid standalone recompilations

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/win_makefile
Fixes #787
I did not include a specific test because (at least on my Windows VM), it needs many objects to trigger this problem, and then the compilation time is also crazily long. I manually verified with one example that had many objects that it failed before and now works.
> [MRG] Don't pass all source files on the command line (C++ standalone on Windows)

- brian2/utils/logger.py
Otherwise, errors raised during Brian's import, before the logging
system is in place, will only lead to the unhelpful error message
`No handlers could be found for logger "brian2"`
This happened to me regularly during development, but we had also cases on the mailing list where this happened to other users (because of problems with the compiled spike queue).
> [MRG] Set up the exception hook only after the logging system has been set up

- brian2/stateupdaters/exact.py
- brian2/tests/test_stateupdaters.py
The equations 
```Python
eqs = '''dv/dt      = (ge+gi-(v+49*mV))/(20*ms) : volt
dge/dt     = -ge/(5*ms) : volt
dgi/dt     = Dgi/(5*ms) : volt
dDgi/dt    = ((-2./5) * Dgi - (1./5**2)*gi)/(10*ms) : volt''' 
```
now fail with an error message (if the method is specified).
I guess I also have to add this somewhere as a test case? in the test_stateupdaters.py file?
> Complex eigenvalues bug

- brian2/codegen/runtime/numpy_rt/templates/summed_variable.py_
- brian2/core/network.py
- brian2/groups/subgroup.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/release_notes.rst
- docs_sphinx/user/synapses.rst
I think we consider this as fixing #766 -- it is a bit hacky (goes through the list of all objects in `Network.before_run`) but does its job.
Connecting to two non-overlapping subgroups is allowed:
```Python
source = NeuronGroup(1, '')
target = NeuronGroup(10, 'v : 1')
subgroup1 = target[:6]
subgroup2 = target[6:]
syn1 = Synapses(source, subgroup1, 'v_post = 1 : 1 (summed)')
syn2 = Synapses(source, subgroup2, 'v_post = 1 : 1 (summed)')
```
(Previously, this was actually raising a confusing error because you could not access the equations from a subgroup. After fixing this, it needed a bit of work to make the numpy target behave correctly).
If the two subgroups overlap you'll get an error:
> NotImplementedError: Multiple "summed variables" target the variable "v" in overlapping groups …
> [MRG] Error for multiple summed vars

- brian2/synapses/synapses.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_synapses.py
This is a rather marginal use case, but in our astrocyte modeling, we need `Synapses` that connect to or from other `Synapses` objects. This works fine in principle, but currently you cannot use `i` and `j` in such `Synapses`, e.g. in `connect` calls. In most cases, you should not use them directly anyway (because the "index" of a synapse is not very meaningful), but currently it might raise an error or do something completely wrong. The reason is that for a connection from a `Synapses` object, `i` will refer to `i` of the source `Synapses` which itself refers to `i` of the synapses's source. This will however be indexed as if it were a variable of the "source synapse". This will do the right thing only by accident, and most of the time will raise an error about incorrect indexing.
This …
> [MRG] Fix the meaning of `i` and `j` in synapses connecting to/from other synapses

- .travis.yml
- appveyor.yml
- dev/conda-recipe/meta.yaml
- setup.py
Require sympy < 1.1 as a workaround for #856
> [MRG] Avoid sympy 1.1 for now

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/user/synapses.rst
I noticed this a while ago but never got around fixing it.
At the moment, the short-hand generator syntax (for single targets per source) does not work with `if`, because something like `connect(j='i if i % 2 == 0')` is translated into `i if i % 2 == 0 for _ in range(1)`.
My commit is a bit of a quick fix, I think we should probably include the parsing of the short-hand code into the `parse_generator_syntax` function in the long run to make the code easier to follow.
Either way, I'd be happy if this could be merged as a short-term solution, I have a use case for this and writing `for _ in range(1)` is really ugly...
> [MRG] Allow the use of "if" in the shorthand generator syntax

- brian2/core/magic.py
- brian2/core/network.py
- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_network.py
- brian2/tests/test_spatialneuron.py
Tests are running quite slow, so I looked a bit into the long-running tests and made some improvements to run them faster. The changes I did don't change much for the total test runtime, but I think they are nevertheless worth having. I made a specific change about integration method/time for the Rallpack2 test (i.e., multicompartmental models), but the other changes are more general:
* I switch off the profiling by default. For tests that don't do much each time step (like many of our tests), it added a considerable overhead. Most of our documentation actually suggested that it was off by default, and if you use `profiling_summary` without switching it on, you get an error message telling you what to do.
* I did some micro-optimisations to the run loop, special-casing simulations with a …
> [MRG] Minor runtime improvements (mostly for tests)

- appveyor.yml
- brian2/codegen/translation.py
- brian2/tests/test_codegen.py
- brian2/tests/test_synapses.py
For the bug description, see #880.
Previously, we redefined a subexpression every time when it was used (just changing between the use of `:=` and `=`). Now, the `subdefined` dictionary does no longer contain `True`/`False` values, but one out of `None`, `'constant'`, `'variable'` instead. If it is already defined *and* constant, then we don't redefine it.
Note that there are some corner cases where we could define a subexpression as constant where we currently don't do it: if the variables on which a subexpression depends change, but the subexpression is not used after that change. I don't think it's worth complicating the logic much just for getting the `const` flag 100% right.
I just fixed another thing I realized while fixing the above bug: you were allowed to write to a subexpression …
> [MRG] Fix subexpression statements

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/makefile
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/synapses.cpp
- brian2/devices/cpp_standalone/templates/win_makefile
- brian2/tests/test_cpp_standalone.py
This branch fixes #882 by only showing the "Number of synapses/spikes" messages in standalone mode when called with `debug=True`. It also changes the approach to debug compilation on UNIX, and enables it for Windows (where previously it only raised a warning).
The change in approach for UNIX: previously, there was a separate debug target in the make file, and compiling in debug mode meant to call `make debug` instead of `make`. Now, using debug mode means creating a make file that includes debug options in the compiler options (i.e., `make` will compile with debug options). The reason is that two separate targets are problematic when they lead to the same output file (in our case `main`), in particular with our new `clean=False` default. If you run the same simulation twice, first with …
> [MRG] Standalone debug output

- brian2/groups/group.py
> [MRG] Use numpy's print options to abbreviate long arrays in warning messages

- .travis.yml
- brian2/codegen/runtime/numpy_rt/templates/group_variable_set_conditional.py_
- brian2/tests/test_neurongroup.py
This is a trivial fix, the code in the template still used `np` for numpy while we replaced it everywhere else by `_numpy` -- apparently that part of the template was never triggered by our test suite (it now is).
To trigger the code and therefore the bug you needed to assign with a condition that evaluated to `False` "in a scalar sense", i.e. not like in `i < 0` which evaluates to `False` for each neuron, but rather like `N < 0`. The simplest example is of course to directly use `False`, i.e.:
```Python
group.v['False'] = 10*mV
```
> [MRG] Fix an error in numpy template, triggered when assigning to a variable with an unfulfilled scalar condition

- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/devices/cpp_standalone/device.py
- brian2/sphinxext/examplefinder.py
- brian2/sphinxext/generate_examples.py
- brian2/tests/features/base.py
- brian2/utils/filetools.py
- dev/benchmarks/openmp/test_openmp_1.py
- dev/benchmarks/openmp/test_openmp_2.py
- dev/benchmarks/openmp/test_openmp_3.py
- dev/benchmarks/openmp/test_openmp_4.py
- dev/ideas/devices/cpp_standalone_run_example.py
- dev/tools/docs/build_tutorials.py
- dev/tools/release/generate_default_preferences.py
- dev/tools/release/prepare_release.py
- dev/tools/release/setversion.py
- dev/tools/run_examples.py
- dev/tools/run_speed_tests.py
- dev/tools/static_codegen/units.py
Only codegen `open` have been fixed. Shall I look for other cases? A quick lookup shows more.
Close #851
> Fix codegen file warnings

- brian2/stateupdaters/base.py
- brian2/utils/caching.py
Gnarg, I just realized that a small but important line got lost when resolving the merge conflicts between the GSL branch and master: the results of the state update code generation were actually no longer cached ;-( This is particularly annoying as it had the most noticeable effect on the runtime improvements for repeated runs. I think it would therefore be good to do a "hotfix" release as soon as possible, hopefully not too many users already tested the performance and were disappointed :-/
> [MRG] Re-add stateupdate caching

- brian2/equations/codestrings.py
- brian2/equations/equations.py
- brian2/tests/test_equations.py
- brian2/units/fundamentalunits.py
- brian2/utils/caching.py
- docs_sphinx/introduction/release_notes.rst
Substituting variables in `Equations` should create a new `Equations` object and leave the original object completely untouched. In violation of this principle, the `Expression` object of the original `SingleEquation` object was replaced (without being used later, probably a left-over from some earlier cleaning up).
This PR fixes this issue (a tiny fix in one line) and adds two tests that failed before the fix (one is about using `Equations.substitute`, the other is triggered by the new caching mechanism). I also tried adding another safeguard to the caching mechanism (returning deep copies of the cached values instead of the values themselves), but it turned out that this itself is fragile (deep copies fail for some sympy objects on some versions) and I therefore removed it again.
> [MRG] Fix bug in Equation's variable substitution mechanism

- brian2/parsing/rendering.py
- brian2/tests/test_synapses.py
In numpy, we were using `*` and `+` to implement logical and/or. This works in general, but can become problematic when the result is used as an index because something like `[0, 0, 1]` is not equivalent to `[False, False, True]`. This could lead to incorrect creation of synapses (see #900).
Why this only manifested recently is unclear, but using arithmetic operators for boolean operations is quite fragile and simply changing the order can change the type:
```pycon
>>> True * False
0
>>> True * False * np.array([True, False])
array([0, 0])
>>> np.array([True, False]) * True * False
array([False, False], dtype=bool)
```
> [MRG] Use `&` and `|` instead of `*` and `+` for logical operations in numpy

- dev/tools/docs/build_dash_docset.py
This script builds a nice docset from the Brian2 docs, which can be used in `Dash.app` or similar clones.
> Added a python script that uses `doc2dash` to build a `Dash.app`-compatible docset for Brian2

- brian2/memory/dynamicarray.py
- brian2/tests/test_memory.py
Otherwise, resizing it will access previously written memory
Fixes #906
> [MRG] Overwrite previously used memory with 0 when shrinking a DynamicArray

- appveyor.yml
- brian2/codegen/generators/base.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/core/clocks.py
- brian2/core/variables.py
- brian2/groups/group.py
- brian2/monitors/statemonitor.py
- brian2/synapses/synapses.py
- brian2/tests/__init__.py
- brian2/tests/test_codegen.py
This PR fixes three issues, the first two directly about the [recent numpy 1.14 release](https://github.com/numpy/numpy/releases/tag/v1.14.0) (~3 weeks ago) and the last a bit more general:
* Our use of `np.issubdtype` raised warnings because of a potential future incompatibility (if I understood correctly that incompatibility does not concern us, but the warning was annoying either way): 
* numpy's print output improved (less unnecessary spaces, etc.), but this of course makes almost all of our doctests fail. For the doctests, I therefore enabled the "legacy mode". Note that the tests only work correctly when run with `brian2.test()` or with one of our scripts, running something like `nosetests --with-doctests brian2` manually will fail (with numpy 1.14).
* Switching between numpy …
> [MRG] Fix numpy 1.14 compatibility issues

- brian2/groups/subgroup.py
- brian2/tests/test_neurongroup.py
See #916 for an explanation of the issue.
The fix is not exactly what I had proposed: we cannot actually change the `scalar` attribute of the variable, because the `variables` dictionary of the referring group only holds a reference to the original `Variable` object. Instead, I added some code to handle this specific situation in subgroups. This is a bit of an ad-hoc fix, but we have to rewrite things quite substantially at some point anyway to deal with the issues described in #276.
> [MRG] Fix handling of linked variables that are scalar in the referring but not in the source group

- appveyor.yml
- brian2/codegen/runtime/cython_rt/templates/spatialneuron_prepare.pyx
- brian2/codegen/runtime/cython_rt/templates/spatialstateupdate.pyx
- brian2/codegen/runtime/numpy_rt/templates/spatialneuron_prepare.py_
- brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
- brian2/codegen/runtime/weave_rt/templates/spatialneuron_prepare.cpp
- brian2/codegen/runtime/weave_rt/templates/spatialstateupdate.cpp
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/spatialneuron_prepare.cpp
- brian2/devices/cpp_standalone/templates/spatialstateupdate.cpp
- brian2/spatialneuron/spatialneuron.py
- brian2/tests/test_spatialneuron.py
Big thanks to @moritzaugustin for pointing out that our three arrays `_ab_star`, `_a_minus` and `_a_plus` (the LHS of the three systems of equations that we solve at every time step) were actually identical! So instead of solving three systems (with a lot of redundant code), we now solve only one (for three RHSs). This simplifies the code quite a bit and also makes things a bit faster.
We previously optionally parallelized over these 3 systems with OpenMP. There was a preference and a heuristic to chose between this parallelization and a parallelization over the branches of the morphology (which should be more efficient with more than 3 branches and more then 3 threads). Since the three systems are now basically solved as one, this choice is obsolete and I documented the preference …
> [MRG] Simplify SpatialNeuron

- brian2/synapses/synapses.py
Just fixing (through the GH online editor) a typo that I noticed when I received an error message:
"...do any..." <- "...to any..."
> Fix minor typo in synapses exception message

- brian2/equations/equations.py
- brian2/equations/refractory.py
- brian2/synapses/synapses.py
- brian2/tests/test_GSL.py
- brian2/tests/test_equations.py
- brian2/tests/test_synapses.py
As discussed in #927 , this PR changes two things:
* `delay` can no longer be used as a variable name in `Synapses`
* The pre-synaptic delay can still be set/accessed using the shorthand `synapses.delay` (instead of `synapses.pre.delay`), but you can no longer reference `delay` in code.
I'm not 100% sure about the latter change: I don't see much use of accessing it in code, but in the long-term we want to have access to it for models of "delay plastiticity" (#355). However, we'd still have to be unambiguous about the syntax to distinguish `pre` and `post` delay. We could simply use `delay_pre` and `delay_post` but then this would be confusing with respect to other `_pre` and `_post` variables which refer neuronal and not synaptic variables. But I think this is something that we should …
> [MRG] Handle delay variable differently

- brian2/codegen/runtime/cython_rt/templates/summed_variable.pyx
- brian2/codegen/runtime/weave_rt/templates/summed_variable.cpp
- brian2/devices/cpp_standalone/templates/summed_variable.cpp
- brian2/tests/test_subgroup.py
As detailed in #925, C-based codegen targets were not correctly setting the values of the target variable to 0 before doing the summation when the target was a subgroup. The fix is straightforward, all that was needed is to add the start index of the target group (which is 0 for standard groups, but potentially >0 for subgroups).
Fixes #925
> [MRG] Fix subgroups and summed variables with C-based codegen targets

- brian2/core/network.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/devices/cpp_standalone/templates/objects.cpp
- brian2/devices/cpp_standalone/templates/synapses_push_spikes.cpp
- brian2/tests/__init__.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_network.py
This is somewhat embarrassing, but in contrast to what I thought, measuring the profiling information in C++ standalone *can* take a significant amount of time. Profiling has been always optional in runtime and recently we switched the default to off for performance reasons. However, in C++ standalone switching off profiling did not change anything. With this PR, profiling becomes optional (it also fixes a minor corner-case issue, where the profiling info would not be reloaded if you reinitialize the device and re-run a s imulation).
The performance difference can be quite striking:
`cuba_openmp`: 0.26-0.27s (this PR); 0.36-0.37s (master)
`STDP_standalone`: 13.4s (this PR); 19.1s (master)
For other examples where the computation within a single code object takes a very long time (e.g. …
> [MRG] Make profiling optional in standalone

- brian2/memory/dynamicarray.py
Fixes a performance regression introduced by commit 9c99e87e279 (a fix for #906; also see comment in #928).
The problem is that when you have a growing data structure such as a `StateMonitor`, it will call `DynamicArray.resize_along_first_dimension`  at every time step to make sure we have sufficient space to store new values. Because we double the underlying array size whenever we run out of space, actual resizing (with data copy) happens rarely. However, with the fix introduced in 9c99e87e, we set the unused part of the underlying array to 0 every time. This was introduced to deal with the case when a resize operation (e.g. in `restore`) *reduces* the size of the array. However, we applied this unconditionally, leading to a large slow-down for long-running simulations with monitors (in …
> Do not unnecessarily set values in dynamic arrays to 0

- brian2/__init__.py
- brian2/codegen/_prefs.py
- brian2/codegen/runtime/__init__.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/tests/test_codegen.py
As discussed in #914, this PR improves Cython's and (to a lesser extent) weave's code generation cache:
1. After successful compilation of a library file for Cython we now delete the corresponding `.cpp` and `.pyx` files, plus any additional temporary library files (I still need to check whether this is working correctly on Windows as well). The library file (e.g. `.so` on Linux) is the only file that we'll ever need later. When I run the Cython test suite with an empty cache, I now get 166MB of cached files instead of 774MB before the change. Quite an improvement! I did not see any noticeable slowdown, and the deletion can be switched off with a preference for debugging (`codegen.runtime.cython.delete_source_files`).
2. When importing Brian 2, if the Cython or weave cache directory take …
> [MRG] Reduce codegen cache size

- brian2/devices/cpp_standalone/templates/objects.cpp
Brian2GeNN does not support profiling but re-uses the `objects.cpp` template.
> [MRG] Only use `profiled_codeobjects` attribute in `objects.cpp` template if defined

- .travis.yml
- appveyor.yml
- brian2/codegen/runtime/cython_rt/extension_manager.py
- dev/conda-recipe/meta.yaml
As discussed earlier (https://github.com/brian-team/brian2/pull/913#issuecomment-360494739), this PR changes our conda packaging to a single package for each architecture, independent of the numpy version. The advantage is that numpy can be updated independently of Brian, and we won't run into problems when anaconda updates to a numpy version that did not exist at the time of our release (currently, this seems to prevent users from installing Brian on top of a recent full Anaconda distribution, see #930, #945). The disadvantage is that nothing prevents a user to run Brian with a new and untested numpy version -- on the other hand, that's already the case when they don't use conda for installation.
Note that in this branch (as in master) the Cython tests still hang sometimes for a certain …
> [MRG] Do not tie conda packages to numpy version

- brian2/synapses/synapses.py
- brian2/tests/test_network.py
> [MRG] Do not delete a previously stored spike queue when using restore

- .travis.yml
- brian2/codegen/generators/GSL_generator.py
- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/codegen/runtime/GSLcython_rt/templates/stateupdate.pyx
- brian2/codegen/runtime/GSLweave_rt/templates/stateupdate.cpp
- brian2/codegen/runtime/cython_rt/templates/common.pyx
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/core/core_preferences.py
- brian2/core/functions.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/groups/neurongroup.py
- brian2/tests/test_GSL.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_functions.py
- brian2/tests/test_refractory.py
- docs_sphinx/introduction/known_issues.rst
- docs_sphinx/user/refractoriness.rst
This introduces a new `timestep` function and uses it for the implementation of refractoriness, as discussed in #949. It's basically done except for a bit of documentation.
A few things to discuss before merging:
* I used a shift of 1e-3dt to be consistent what we are doing in `SpikeGeneratorGroup`, not sure whether a smaller shift would be better...
* the implementation of the `timestep` function is slightly complicated by the fact that the time of the last spike is `-inf` before the first timestep. My handling of all this in the numpy implementation is probably not optimal, I'm seeing something like a 2% slowdown for the COBAHH example.
* I added a preference to switch back to the old behaviour -- not sure it's well explained and named, though (`core.legacy_refractory_timing`). Maybe we …
> [MRG] Introduce timestep function to avoid rounding issues in refractoriness

- brian2/codegen/generators/numpy_generator.py
While I only saw a minor slow down for the numpy target with the COBAHH example due to the introduction of the `timestep`, I just realized that simpler examples are much more affected. One of them is part of our benchmarking: https://brian-team.github.io/brian2_benchmarks/#benchmarks.FullExamples.time_reliability_example
I found that due to the way that I added the `timestep` function, Brian thought that the function *requires* quantities instead of simple floats/arrays and was therefore helpfully converting the floats/arrays that we are using during simulation to quantities and back. Not only the conversion itself itself is somewhat costly, but arithmetic operation on quantities are also significantly slower due to the additional checks and unit conversions.
> [MRG] The `timestep` function should not use `Quantity` objects during a simulation

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
See problem description in #966. In addition to that issue, this PR also fixes an inefficiency when dividing large quantities by a unit (most commonly used to remove units, e.g. `mon.t/second`)
> [MRG] Fix inefficiencies in the Quantity/Unit implementation

- brian2/__init__.py
- brian2/codegen/__init__.py
- brian2/codegen/translation.py
- brian2/core/base.py
- brian2/core/core_preferences.py
- brian2/groups/__init__.py
- brian2/input/__init__.py
- brian2/monitors/__init__.py
- brian2/only.py
- brian2/spatialneuron/__init__.py
- brian2/stateupdaters/__init__.py
- brian2/synapses/__init__.py
- brian2/tests/test_functions.py
- brian2/tests/test_synapses.py
- brian2/units/fundamentalunits.py
- brian2/utils/__init__.py
This PR reduces the number of names that get imported with a `from brian2 import *`, by adding `__all__` definitions and a few code rearrangements in `brian2.__init__`.
We still import many names that users will most likely never need (e.g. `NumpyCodeObject`), but I was rather conservative in removing names to avoid breaking existing code.
The following **functions** are no longer added to the namespace:
```
analyse_identifiers, brian_object_exception, c_data_type, default_float_dtype_validator, 
dtype_repr, get_identifiers_recursively, make_statements, weakproxy_with_fallback
```
There's actually one new function: `binomial` now refers to numpy's `binomial` function, it was previously shadowed by our module of the same name (see below).
The following **modules** (some are Brian modules, …
> [MRG] Add less names to the namespace when using wildcard imports

- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/core/functions.py
- brian2/tests/test_functions.py
I noticed two bugs in our recently introduced `timestep` function and fix them in this PR:
1. In the documentation we state: 
> This function can handle infinity values, it will return a value equal to half of the maximal integer value. This assures that an expression such as `timestep(t) - timestep(lastspike)` will result in a reasonable value even if `lastspike` is `-inf`.
This was actually only true for the numpy implementation, C++ and Cython still returned the minimum/maximum possible integer, leading to potential overflow issues.
2. If you declare a variables as `: integer` in equations, it will by default use a 32bit integer. Now, such a variable might be a natural way to store a timestep calculated with the `timestep` value. Unfortunately,  the "maximum integer" that we divide by …
> [MRG] `timestep` function: implement the "overflow-safe" infinity value for C++/Cython

- docs_sphinx/advanced/scheduling.rst
As discussed in issue #976, I made the following changes (in order of file differences):
1) Add a default `toolbar_width`.
2) Actually use the `toolbar_width` in `__call__` instead of a preset.
3) Pass the progress bar in the correct manner to `run`.
> Fix issue #976 (Documentation fix: ProgressBar code)

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
[Sorry for the spam, here's the new PR]
If you use non-linear synaptic equations like the ones in PR #995, currently Brian will allow you to mark them as (event-driven), but since it cannot solve them exactly, it will solve all equations independently. This gives wrong results, because it does not take the development of the other variables during the time between updates into account.
This PR does nothing fancy to handle such equations, it just raises an error if the situation occurs.
> [MRG] Raise an error for event-driven equations that are non-linear and not independent

- brian2/codegen/generators/GSL_generator.py
- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/core/functions.py
- brian2/groups/neurongroup.py
- brian2/tests/test_functions.py
See discussion in #991 . The changes in this PR are:
* `timestep` function is no longer safe to use with infinity values
* `timestep` function uses `int64` to avoid overflow
* Instead of setting `lastspike` to `-inf*second` for neurons that never spiked, we now set this value to `-10000*second`
* C++ and Cython code generation has been refactored so that scalar variables are read in the scalar code block (i.e. outside of the loop), regardless of whether they are used in the scalar or vector code. This is particularly relevant for `dt` and `t`.
The last change speeds up things considerably, even though the use of `int64` slows down things again. Nevertheless, if we are looking at the time the stateupdater takes in the context of a real simulation (CUBA example), this all now looks pretty …
> [MRG] Optimization for refractoriness calculation

- brian2/groups/group.py
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/user/equations.rst
- docs_sphinx/user/synapses.rst
Following the discussion in #979 (and as an alternative solution), this PR:
* Only creates a `lastupdate` variable if it is used by Brian automatically, i.e. for `event-driven` synapses.
* Tells the user that they have to add the variable manually, if they try to access it.
This breaks backwards-compatibility for users that manually used `lastupdate`, but I think with the error message, this should be ok. There's rarely a use case for doing this manually instead of using the `event-driven` mechanism.
The check whether a user tries to access `lastupdate` is a bit ugly, directly in `groups.py`, but I think it is worth it, given that we do not want to silently break backwards-compatibility.
> [MRG] Remove lastupdate variable, except for event-driven

- brian2/codegen/optimisation.py
- brian2/devices/cpp_standalone/device.py
- brian2/parsing/bast.py
- brian2/tests/test_GSL.py
- brian2/tests/test_poissongroup.py
- brian2/tests/test_refractory.py
- brian2/tests/test_synapses.py
This avoids generating many intermediate values in double precision, even when the `core.default_float_dtype` preference is set to `float32`. Does not seem to have much impact on speed, though (using script from #1001).
> [MRG] Single precision everywhere

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/main.cpp
This adds four new code slots that can be used with `device.insert_code`: `before_start`, `after_start`, `before_end`, `after_end`. With this we can add code before/after things like loading static arrays from disk or writing the results to disk.
This offers as an alternative for benchmarking and replaces #1002.
> [MRG] Standalone code slots

- brian2/stateupdaters/exponential_euler.py
- brian2/tests/test_stateupdaters.py
In principle the exact state updater should of course also be able to handle such equations, but I have to think a bit more about how to implement this. For now, this solves the original problem of the OP from #1010  who wanted to use `exponential_euler` (in the context of a multicompartment model).
Fixes #1010
> [MRG] Make the exponential_euler state updater handle constant RHS equations

- brian2/core/base.py
Leads to a more useful display of syntax errors in ipython notebooks
Fixes #964 
This seems to be the right thing to do. Error message in a jupyter notebook for a `SyntaxError` (see #964) before this change:
```
File "<string>", line unknown
BrianObjectException
```
After this change:
```
File "<unknown>", line 1
`False
^
BrianObjectException: unexpected EOF while parsing
```
It does not seem to affect other error messages or error messages outside of notebooks/ipython.
> [MRG] Copy over public attributes in DerivedBrianObjectException

- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/spikemonitor.cpp
- brian2/devices/cpp_standalone/templates/statemonitor.cpp
- brian2/input/spikegeneratorgroup.py
- brian2/monitors/spikemonitor.py
- brian2/monitors/statemonitor.py
- brian2/tests/test_spikegenerator.py
As discussed in #1017 , spikes that fall before the current time (set between runs with `set_spikes`) are now ignored and a warning is issued. To make this work with standalone, I had to make some minor adjustments to the way read-only variables are marked as "dirty" by code writing to them.
Fixes #1017
> [MRG] Warn when SpikeGeneratorGroup sets spike times < current time 

- brian2/codegen/generators/numpy_generator.py
- brian2/tests/test_synapses.py
See #1024, trivial fix (finding the actual issue took way more time ;) ).
> [MRG] Fix _vectorisation_idx definition in numpy fallback loop for synapses

- docs_sphinx/introduction/release_notes.rst
I'd like to do a new release soon (maybe later today?), given that the annoyances around py-cpuinfo and Cython will lead to more and more user issues as time passes. Not sure whether it should be 2.2.1 or 2.2.0.1, given that there are few big changes.
> [MRG] Add release notes for version 2.2.1

- brian2/codegen/runtime/cython_rt/templates/synapses_create_generator.pyx
- brian2/codegen/runtime/numpy_rt/templates/synapses_create_generator.py_
- brian2/codegen/runtime/weave_rt/templates/synapses_create_generator.cpp
- brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- dev/tools/run_nose_tests_standalone.py
This should fix #1037 -- note that the relevant (newly added) tests are part of a "long" test, i.e. they will not run by default (including on the test servers).
Oh, and with the change synapse generation is slightly less efficient when using `skip_if_invalid`, because the post-synaptic condition will be evaluated for non-existing targets. However, I think this is enough of a corner case that it does not merit to further complicate the (already quite complicated...) template.
> [MRG] Check range of synaptic targets after applying post-synaptic condition

- brian2/codegen/runtime/cython_rt/templates/spikegenerator.pyx
- brian2/codegen/runtime/numpy_rt/templates/spikegenerator.py_
- brian2/codegen/runtime/weave_rt/templates/spikegenerator.cpp
- brian2/core/variables.py
- brian2/devices/cpp_standalone/templates/spikegenerator.cpp
- brian2/input/spikegeneratorgroup.py
- brian2/tests/test_network.py
- brian2/tests/test_neurongroup.py
This should fix #1043. The PR speeds up things, but it seems that the current integer-based code is still slower than the previous float-based code. I don't see any obvious reason for this. Well, it is probably not worth spending much time on this, given that performance is never great with the `numpy` codegen target.
> [MRG] Expose integer timestep

- brian2/codegen/codeobject.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/codegen/runtime/weave_rt/weave_rt.py
- brian2/core/functions.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/device.py
- brian2/tests/func_def_cpp.cpp
- brian2/tests/func_def_cpp.h
- brian2/tests/func_def_cython.pxd
- brian2/tests/func_def_cython.pyx
- brian2/tests/test_functions.py
- docs_sphinx/advanced/functions.rst
- examples/advanced/opencv_movie.py
- setup.py
When writing functions with target-specific native, non-trivial code (e.g. as in the [OpenCV example](https://brian2.readthedocs.io/en/stable/examples/advanced.opencv_movie.html)), you might have to use additional header files and libraries. We already support this via preferences which is motivated by standalone where you compile everything at once. For runtime targets like weave or Cython, we do not need to compile every code object file with these additional arguments, but only those where the function is used (potentially this could speed up compilation, but not sure it makes a practical difference).
Finally, we currently do not support to put the code in a completely separate file and compile it with the Brian-generated files. With this PR, this is possible by providing the separate …
> [MRG] Allow compiler keywords in function implementations

- brian2/groups/neurongroup.py
- brian2/spatialneuron/spatialneuron.py
- brian2/tests/test_spatialneuron.py
- brian2/tests/test_subgroup.py
- docs_sphinx/user/models.rst
- docs_sphinx/user/multicompartmental.rst
Sometimes, especially in the context of `SpatialNeuron`, you might want to refer to only a single element as a subgroup. For this, you'd previously have to use an awkward slice such as `group[2:3]`. With the changes here, you can use `group[2]` instead. You can also use arrays, e.g. `group[[3, 4, 5]]` instead of `group[3:6]`, which again is something that is useful for `SpatialNeuron`, where you can get such indices from the `Morphology` object (e.g. `morpho.dend.indices[:]` will get the indices of the `dend` section).
It's not a big feature, but it adds a bit of consistency/flexibility, I think. Under the hood, it doesn't change anything, subgroups still have to be contiguous.
> [MRG] Add new ways to create subgroups (e.g. with single numbers or arrays)

- brian2/hears.py
- docs_sphinx/introduction/brian1_to_2/brian1hears_bridge.rst
- docs_sphinx/introduction/changes.rst
Just updated warnings and docs to reflect that we will deprecate brian2.hears in favour of brian2hears.
> Start deprecating brian2.hears

- brian2/input/spikegeneratorgroup.py
- brian2/tests/test_spikegenerator.py
In `SpikeGeneratorGroup`, we use variables directly stored in the object (i.e. not as `Variables`) to decide whether we need to rebuild the integer timestep representation of spike times (e.g. when `dt` has changed between runs). In principle, we *could* store them as "proper" variables, but that would also be somewhat inconvenient: e.g. we currently set `_previous_dt = None` to note that the simulation has not been run yet; if it were a variable using our full machinery, then it would necessarily have to store a value in seconds,  so we'd need some workaround like `_previous_dt = 0*second` to denote "not run yet".
With this PR I opted for the straightforward solution to fix #1084: we now manually store/restore the two internal variable values.
Using proper variables might have been a …
> [MRG] Correctly store/restore internal `SpikeGeneratorGroup` state

- docs_sphinx/developer/GSL.rst
- docs_sphinx/developer/equations_namespaces.rst
- docs_sphinx/developer/guidelines/documentation.rst
- docs_sphinx/introduction/install.rst
Checked the documentation and updated out-of-date items, however I felt everything is updated on sections other than `Introduction` and `Developer's Guide` as other sections are mostly docstring generated. 
Kindly correct me if anything is incorrect. Please mention any particular sections which I would have possibly missed out and likely to need update.
> Update documentation by removing broken links and obsolete locations

- dev/tools/docs/build_tutorials.py
- docs_sphinx/conf.py
- docs_sphinx/introduction/index.rst
- docs_sphinx/introduction/install.rst
- docs_sphinx/introduction/scripts.rst
- docs_sphinx/user/models.rst
- docs_sphinx/user/numerical_integration.rst
- docs_sphinx/user/recording.rst
- docs_sphinx/user/synapses.rst
This PR updates/improves several parts of the documentation. The most important changes:
* the installation instructions have been shortened to no longer mention the conda development packages (which we haven't been building for a while), the complicated instructions for running code generation on Windows with Python3.4 (which is officially no longer supported), or the various ways to install/update `pip` (it is pre-installed by default now)
* new documentation for Python beginners, briefly explaining the various ways to run Brian code (jupyter notebook, etc.)
* new sections in the monitor/synapses documentation, detailing how to do common tasks (e.g. freeing up memory during a simulation, using synaptic matrices, ...)
> [MRG[ Documentation updates

- LICENSE
- brian2/codegen/generators/base.py
- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/optimisation.py
- brian2/codegen/translation.py
- brian2/core/functions.py
- brian2/core/network.py
- brian2/core/variables.py
- brian2/input/binomial.py
- brian2/parsing/bast.py
- brian2/parsing/rendering.py
- brian2/parsing/sympytools.py
- brian2/synapses/parse_synaptic_generator_syntax.py
- brian2/synapses/synapses.py
- brian2/tests/test_functions.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_stateupdaters.py
- docs_sphinx/advanced/functions.rst
This will need a bit of explanation...
When the user includes a call to `rand()` or `randn()` in the code, the generated code will be actually `rand(vectorisation_idx)`. This is necessary for the numpy target, because we have to know how many random numbers the function call should return. `vectorisation_idx` will be an array of all neuron indices e.g. in the state updater, but only a subset of the indices when used as part of e.g. the reset. In C-based code generation targets, `vectorisation_idx` will always be a single (e.g. neuron) index, which could be potentially useful to generate the same random numbers independent of execution order in OpenMP. This is not implemented yet, though, so C-based targets simply ignore this argument.
Note that an alternative solution to this issue would …
> [MRG] Revisit use of vectorisation_idx in function + add poisson function

- brian2/codegen/runtime/cython_rt/templates/ratemonitor.pyx
- brian2/codegen/runtime/numpy_rt/templates/ratemonitor.py_
- brian2/codegen/runtime/weave_rt/templates/ratemonitor.cpp
- brian2/devices/cpp_standalone/templates/ratemonitor.cpp
- brian2/monitors/ratemonitor.py
- brian2/tests/test_monitor.py
In C++-based targets, the stored length of the recorded timepoints/rates were not correctly updated. Indexing with slices would then return empty arrays. The fix is the same as we did a while ago for `SpikeMonitor`: update "N" (the total number of time points/rates stored) from within
the template code.
The issue is only triggered in standalone mode, although for consistency the change has to be made everywhere. It can be reproduced with something like this:
```pycon
>>> from brian2 import *
>>> set_device('cpp_standalone')
>>> group = PoissonGroup(10, rates=100*Hz)
>>> mon = PopulationRateMonitor(group)
>>> run(1*ms)
>>> mon.t
<ratemonitor.t: array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]) * msecond>
>>> mon.t[:5]
array([], dtype=float64) * second
```
There are easy workarounds …
> [MRG] Fix an issue with indexing in `PopulationRateMonitor`

- brian2/core/network.py
Fixes two issues with progress reports in runtime mode:
* Reports were using just the floating point value instead of a value with units (e.g. `0.95` instead of `0.95 s`)
* Reports were displaying the progress incorrectly for runs that did not start at 0s (#1116).
Both fixes are rather trivial...
> [MRG] Improve progress reports

- brian2/codegen/optimisation.py
- brian2/devices/cpp_standalone/device.py
- brian2/equations/codestrings.py
- brian2/equations/equations.py
- brian2/parsing/bast.py
- brian2/parsing/expressions.py
- brian2/parsing/rendering.py
This is a bit of a quick-and-dirty fix for #1130, but it makes the test suite run with Python 3.8 on my machine (after merging #1127, I'll make the automatic test suite run tests on Python 3.8 as well). This is quite urgent, since you'll now get Python 3.8 if you install it from www.python.org or create a new environment with `conda`.
The problem is that with Python 3.8, number literals like `17.4` or `42`, as well as other constants such as `True` or `None` are represented as `Constant` objects in the AST, whereas previously numbers where `Num`, and the others were `NameConstant`.
We could certainly simplify all this a bit, but this will also be easier when we no longer have to worry about supporting Python 2.
> [MRG] Fix compatibility with Python 3.8

- brian2/core/magic.py
- brian2/core/network.py
- brian2/devices/device.py
- brian2/tests/test_devices.py
- brian2/tests/test_network.py
[Note that this is currently built on top of the pytest branch, so don't merge it as it is]
During the discussion in #1124 I realized that our store/restore mechanism could be even more powerful with a little added feature. Currently, it restores the full network state but not the state of the random number generator. This is often what you want, e.g. to run a stochastic sampling of the same simulation. However, there are also situations (like the one by the user in #1124), where you *do* want to restore the state so that a simulation can be reproduced exactly starting at a snapshot point. This feature isn't difficult to add, so I made two changes:
* The  `store()` call always stores the random number generator state (including the buffer, that's on the order of a couple of KB, so …
> [MRG] Restore random state

- brian2/core/magic.py
- brian2/core/network.py
- brian2/devices/device.py
- brian2/tests/test_devices.py
- brian2/tests/test_network.py
Oops, opening this again because I accidentally merged #1131 into the `pytest` instead of into the `master` branch. Will go ahead with the merge into `master` right away.
> [MRG] Add support for storing/restoring the random number generator state

- appveyor.yml
- brian2/codegen/generators/GSL_generator.py
- brian2/codegen/generators/cpp_generator.py
- brian2/conftest.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/win_makefile
- brian2/tests/__init__.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_functions.py
- dev/conda-recipe/meta.yaml
- setup.py
While debugging an error that only occurred under Windows (more on this later) I noticed that our technique for finding `vcvarsall.bat`(via `msvc9compiler.find_vcvarsall`)  does not work for Visual Studio 2019. There is a new function in setuptools that is meant to be used for more recent Visual Studio versions (from 2015 on, I think). This function works a bit differently, it does not return the `vcvarsall.bat` filename but instead directly a dictionary with all environment variables. With this PR, we support this way of configuring the compiler environment as well. The code is currently a bit long and messy, but we could potentially simplify it when we drop Python 2.7 support and no longer need to support Visual Studio 2008. 
There are a few other minor standalone-related changes:
* We …
> [MRG] Improve Visual Studio support on Windows

- brian2/sphinxext/generate_examples.py
- dev/tools/docs/build_tutorials.py
- docs_sphinx/index.rst
Current Binder links in sphinx docs point to the wrong place, this fixes that.
> [MRG] Update Binder links to point to the right place

- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/utils/filelock.py
- docs_sphinx/introduction/known_issues.rst
- docs_sphinx/user/computation.rst
Even though it did not fix issue #1154 after all, I still think it is preferable to use the `filelock` module from https://github.com/benediktschmitt/py-filelock instead of our own solution. The approaches are basically the same, but the `filelock` module makes more effort to release locks in case of exceptions, etc. I included it directly in our utils package, since it is a single file and released into the Public Domain, so this seemed easier than adding a new dependency (it also allows us to downgrade the log level, otherwise we'd get messages about acquired/released locks by default...). 
This PR also documents the issue discussed in #1154, and I'd therefore say it closes #1154.
> [MRG] Use filelock module

- brian2/synapses/synapses.py
- brian2/tests/test_functions.py
This makes sure that checks like `check_expression_for_multiple_stateful_functions` work.
Closes #1146
> [MRG] Resolve variable/function names before creating abstract code in Synapses

- brian2/equations/equations.py
- brian2/tests/test_spatialneuron.py
- docs_sphinx/introduction/release_notes.rst
We previously removed the `point currents` flag when converting a `constant over dt` subexpression into a parameter. With this PR, all flags are conserved.
Fixes #1160
> [MRG] Correctly handle point currents marked as constant over dt

- brian2/codegen/cpp_prefs.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/main.cpp
- brian2/devices/cpp_standalone/templates/network.cpp
> [GSoC 2020] change output in standalone mode to standard mode (hour/minute/seconds)

- docs_sphinx/advanced/scheduling.rst
> [Gsoc 2020] add example in documentation for printing progress bar in standalone mode

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_cpp_standalone.py
This avoids relying on the instance tracker (and garbage collection, etc.) which might contain objects from previous runs.
Fixes #1189
@fpbattaglia: could you check whether this branch (`standalone_networks`) fixes your issue also in the more complex code?
The solution used here actually simplifies the code, so I think it makes sense to use it.
> [MRG] Only consider networks used in runs when building standalone code

- brian2/utils/logger.py
Instead of a plain `FileHandler` the debug log is now logged using the `RotatingFileHandler` which allows us to specify a maximum file size. (Hard coded to 10MB but if needed, I can change the value or make it configurable.)
Note that the `RotatingFileHandler` currently needs to create at least one backup file for the mechanism to work, which means that we have to account for this in the cleanup function.
> Use rotating log handler to keep debug log from growing out of bounds.

- brian2/core/variables.py
- brian2/tests/test_neurongroup.py
We implement arithmetic operations on `VariableView`, so that `group.v + 3*mV` does not raise an error due to `group.v` being a `VariableView` (with support for `group.v['v > -70*mV']`, etc.) and not a `Quantity`. As @romainbrette noticed, we did not implement the power operation, so while `group.v * group.v` would work, `group.v ** 2` would not (but you could always use the workaround `group.v[:]**2`).
This PR adds the support for the power operation and – rather for completeness than for usefulness – also for the in-place operations `//=`, `%=`, and `**=`. I also realized that we did not have any tests for the in-place operations, so I've added them as well.
This is ready-to-merge. I think I'll stop using the `[MRG]` or `[WIP]` markers in the title of the pull requests now that github …
> Variableview operations

- brian2/tests/__init__.py
- brian2/tests/pytest.ini
- brian2/tests/test_GSL.py
- dev/continuous-integration/run_test_suite.py
Users running `brian2.test()` will see many errors if the GSL is not correctly installed. It gets automatically installed with the conda package, but if you install via pip it is up to you to install it. While the error message clearly states that you need to install the GSL, it's not great for users to see tens of tests failing for an optional dependency that only a few of them will ever use.
With this PR, all GSL tests are marked with a pytest `gsl` attribute and excluded if you run `brian2.test()`, you'll have to explicitly ask for them with `brian2.test(test_GSL=True)`. Nothing changes on the test servers, we simply switch on the `test_GSL` option in the `run_test_suite.py` script that we use there.
> Make GSL tests optional

- brian2/codegen/translation.py
- brian2/equations/equations.py
- brian2/parsing/bast.py
- brian2/parsing/rendering.py
- brian2/stateupdaters/explicit.py
- brian2/stateupdaters/exponential_euler.py
- brian2/tests/test_codegen.py
As noted in #812 , we always converted integers to float whenever we use sympy (most importantly for differential equations). Back in the days we could not fix it because it led to problems with floor division. This has been fixed in sympy quite a while ago, in sympy 1.1 (we already require sympy >=1.2), so this is no longer an issue. With this PR, we take care to represent integers as integers in sympy, which fixes #1199 .
Note that there are still places where we convert integers to floats that are unrelated to sympy. For an expression `x + 1`, where `x` is a floating point variable (and therefore the whole expression is floating point), we try to rearrange things during the optimization step (e.g. to replace `x + 0` by `x`), which leads to the expression being converted to `x + 1.0`. …
> Handle sympy integers

- .travis.yml
- brian2/tests/test_neurongroup.py
- brian2/tests/test_parsing.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spatialneuron.py
- brian2/tests/test_synapses.py
- brian2/tests/utils.py
- dev/tools/run_tests.py
- dev/tools/run_tests_standalone.py
Hey there,
I just adapted one of the brian2 tests to make it standalone compatible. I don't think this changes anything for what is tested here. In general, I sometimes come across a brian2 test that could be made standalone compatible. In the past I just added those tests to the brian2cuda tests. But I could also just add them to brian2 as here, would you want that?
And I am currently adding more tests for setting the RNG seed. In brian2cuda the random number generation is quite different depending on where it is used (synapse connection conditions use host side RNG, stateupdaters etc. use a device side random number buffer and binomial uses on the fly device side RNG). Do you want such tests in the brian2 test suite or should I keep them in brian2cuda? I guess brian2 uses the same RNG …
> Make RNG seed test standalone compatible

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
- docs_sphinx/developer/units.rst
This implements numpy's `matmul` function and the `@` operator to correctly work with units.
As @kjohnsen mentioned in #1212, functions like `numpy.linalg.norm` do not work with units, but for now I decided to just mention that functions in subpackages like `linalg` are not supported. For many of them it would not be complicated to add support, but others will need a closer look (in the worst case, they might have options that change the units of the result).
I'd say this fixes #1212 for now.
> Correctly deal with matmul and document unsupported functions

- brian2/codegen/codeobject.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/numpy_rt/numpy_rt.py
- brian2/core/base.py
- brian2/core/network.py
- brian2/equations/equations.py
- brian2/groups/group.py
- brian2/tests/test_GSL.py
- brian2/tests/test_functions.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_numpy_codegen.py
- brian2/tests/test_poissongroup.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_stateupdaters.py
- brian2/tests/test_synapses.py
- brian2/utils/logger.py
- docs_sphinx/introduction/compatibility.rst
Fixes #1183 
This replaces our hand-crafted `BrianObjectException` (which inherits from both `BrianObjectException` and the actual exception that was raised, and includes the stacktrace of the original exception) by exception chaining. In Python 2, we did not have another choice, but I think in Python 3 this is clearly an improvement, because:
1. Our exception type sometimes made problems during development (I don't remember the details, but working on Brian itself sometimes lead to errors where the `BrianObjectException` could not be constructed, completely hiding the actual problem).
2. In Python 3 our previous solution leads to a lot of redundancy in the exception traceback (see example below).
The are two open points before merging:
1. The current implementation uses exception …
> Brian obj exception

- brian2/codegen/generators/cpp_generator.py
Just a wrong function argument that had no effect other than confusing me for a bit.
> Remove unused get_array_name argument

- brian2/parsing/expressions.py
- brian2/synapses/synapses.py
- brian2/tests/test_parsing.py
- brian2/tests/test_synapses.py
This fixes #1218 (see comments in there). If a string condition or a probability as a string expression is provided to `Synapses.connect`, these will now be checked for syntax/unit correctness.
As a little bonus, `SyntaxError`s that are raised (e.g. about an incorrect number of arguments), now mention the full expression that caused them together with the little `^` arrow pointing at the place where it happened.
> Synapse connect errors

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/user/synapses.rst
See my comment in this [briansupport thread](https://groups.google.com/g/briansupport/c/aJK29Kiloxw/m/T1eadGyFBQAJ). This adds support for:
* `len(S[0, :])` and similar expressions (before only e.g. `len(S[0, :].i)` worked)
* support for `N_outgoing_pre` and `N_incoming_post` as attributes of `Synapses`, which give access to the same information as `N_incoming` and `N_outgoing`, but on a per-neuron instead of on a per-synapse basis. The implementation is simple – in principle we could also use something fancier using a reference and indicies, but then the variables would be available to use in code where you cannot use them correctly (synaptic code will always loop over synapses, not over neurons)
> Synapse information

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
See comments in #1227. I don't think `N_incoming`/`N_outgoing` in the `connect` statement is something that we should support (but we *should* fix #664 at some point...).
Closes #1227
> Do not allow N_incoming/N_outgoing in Synapses.connect

- brian2/spatialneuron/spatialneuron.py
If you install Brian2 via pip, it is possible that you don't install scipy (since it is not strictly necessary). For `SpatialNeuron`, this means that simulation will be very slow when run with `numpy`. We therefore raise a warning, but the warning tested whether the `CodeObject` is an instance of `NumpyCodeObject`. This is of course true for `numpy`, but it is unfortunately also true for `CythonCodeObject` which inherits from it. This trivial fix checks for the exact type instead.
> Remove false warning for SpatialNeuron when using Cython

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_cpp_standalone.py
Header/source files were gathered in lists, and therefore the same code was included several times in the make file. Using sets instead of lists to remove the duplicates seems to fix the issue. Let's wait for confirmation from @mdepitta that it also works with his more complex code.
Fixes #1237
> Do not duplicate header/source file names in Makefile

- brian2/utils/logger.py
Given [@mstimberg's comment](https://groups.google.com/g/brian-development/c/N61MUSEfU64) on the brian-development list, I'm guessing error messages should also point to discourse.
> Point unresolved error message to discourse forum [ci skip]

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
I've committed a test case that demonstrates the issue:
```python
source_dt = 0.1*ms
synapse_dt = 1*ms
source_target = NeuronGroup(1, 'v:1', dt=source_dt, threshold='False')
synapse = Synapses(source_target, source_target, 'dw/dt = 1/ms : 1 (clock-driven)', 
dt=synapse_dt, method='euler')
synapse.connect()
synapse.w = 0
run(1*ms)
assert synapse.w[0] == 1
```
The issue is that `synapse.w[0]` will be `0.1` because `Synapses` uses the `NeuronGroup`'s `dt` for scaling the constant `1` in the equation, but `Synapses` uses its own `dt` for the actual timestep.
I have found the source of the issue, the `SynapseGroup`'s `dt` variable is being prefixed with `_clock_`, why that is I am not sure of.
Removing the prefix fixes my issue and still all tests in `test_synapse.py` pass, but I do not …
> Synapses is not resolving dt correctly.

- brian2/units/fundamentalunits.py
This is a micro-fix: I noticed that our LaTeX export for `Quantity` objects was slightly off, it added a space between the scale and the unit symbol which is wrong and makes for confusing compound units. This removes the space, so a space is now only added between the separate units. A fairly non-controversial change, I think :)
LaTeX output for `print(sympy.latex(ms*pA))`
Before:
After:
> Remove incorrect space in LaTeX representation of units

- docs_sphinx/user/refractoriness.rst
I have made small changes to the Refractoriness file in the User's guide.
I have changed the word 'changing' to 'varying' because I felt that it was more appropriate in the context.
I have also changed the 'to prevent to count' to 'to prevent the count of'.
> Minor changes to the Refractoriness file in the User's guide

- brian2/equations/equations.py
- docs_sphinx/user/models.rst
As reported in the [discourse forum](https://brian.discourse.group/t/multiple-independent-sources-of-noise-in-single-neuron-model/212), the error message for multiple uses of `xi` is not very helpful, and the main documentation does not directly point to the solution either. This PR makes the error message quite verbose (but hopefully clear) and adds a link to the documentation pointing to the place where this issue is discussed.
> Improve error message for multiple uses of `xi` and add link to docs

- brian2/devices/cpp_standalone/templates/synapses_push_spikes.cpp
- brian2/tests/test_cpp_standalone.py
Hello,
I've encountered an issue with `profile=True` in standalone mode where the generated code would fail to compile. It turned out, that the code generator duplicated the profiling lines for `synapses_push_spikes` which led to a duplicated variable definition. Removing them once fixed the issue for me.
The same code is already included at the end of templates/common_group.cpp,
and currently prevents compiling code involving synapses with profile=True.
The unittest failed before, but should be passing now.
> Remove duplicated profiling code in codegen.

- .github/workflows/publish_to_pypi.yml
- brian2/codegen/cpp_prefs.py
- brian2/tests/test_codegen.py
- dev/continuous-integration/run_simple_test.py
This PR makes github action build binary wheels for all platforms and uploads them to PyPI for tagged releases (and to TestPyPI for all commits). This makes for a rather impressive list of files, including wheels for the brand-new Apple machines with an ARM chip :), see https://test.pypi.org/project/Brian2/2.4.2.post0.dev90/#files
This seems to work well, and will installation much better/quicker for users that install with `pip` (actually, we might even reconsider our recommendation to use `conda`). There's one thing that is left to do which is only tangentially related to building the wheels: on some OS X installations, `/usr/bin/gcc` is actually a symlink to the `clang` compiler. This is fine in general, as both are mostly compatible. However, this fails with our default `gcc` …
> Build binary wheels

- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
Hello @mstimberg,
As discussed in #1263, I have added the check for cases where the summed variables are referring to event-driven variables. Here I have used a recursive function to check for the additional cases that you pointed out instead of using the `get_substitued_expression()` function because the `get_substitued_expression()` function was not giving me the desired result. Also, I have defined the recursive function inside the `__init__` because this function will not be needed anywhere outside the `__init__` method. What are your thoughts?
Since we have not yet decided whether we need an error or a warning, I have placed a temporary print statement in its place for now. I will modify it as soon as we reach a decision.
> Error/Warning for Summed Variable Pointing to Event Variable

- brian2/codegen/cpp_prefs.py
Greetings,
While integrating the package _brian_ in the Debian project with @mr-c, we tried to get the package to build and test seamlessly on all architectures possible supported by the project without the need for users to change the default build options in _brian2/codegen/cpp_prefs.py_.  You can see for instance a summary of the [latest _brian_ build and test results per architecture during the upload to _experimental_](https://buildd.debian.org/status/package.php?p=brian&suite=experimental) on the build servers status page.
Would you be interested to have such a default build options selector upstreamed?
The present version only matches the architectures on which I believe it might be possible to do some testing on real hardware; thus no SuperH, nor x32, due to missing build …
> Provide fair defaults build flags to several archs

- brian2/devices/cpp_standalone/device.py
- brian2/tests/test_cpp_standalone.py
This fixes #1276, the problem that external constants were unconditionally search&replaced in the final generated code which could lead to unexpected results for external constants named `x` for example (which we use in several places as function arguments).
At first, I thought this would be easy to fix by just replacing constants in the abstract code instead of in the final code which includes all the function definitions. But I then realized that we use the `freeze` mechanism also to replace constants outside of user code, e.g. templates might refer to `N` as the number of neurons which is represented as an "external constant" as well. The easiest way to fix it that I found was to use the mechanism that we already use for constants such as `_num_arrayname` that we add to give the code …
> Add constant definitions instead of replacing them in the code for standalone mode

- brian2/core/clocks.py
- brian2/core/variables.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/input/timedarray.py
- brian2/synapses/spikequeue.py
- brian2/synapses/synapses.py
- brian2/tests/test_codegen.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_units.py
- brian2/tests/test_variables.py
Numpy type aliases are deprecated since numpy 1.20 and using e.g. `np.bool` over `bool` does not add anything. This PR therefore removes all unnecessary type aliases. Note that types like `np.int32` or `np.float32` are still useful (and not deprecated), since Python does not have any builtin equivalents.
See https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> No longer use deprecated numpy type aliases

- brian2/groups/neurongroup.py
Issue:
Because of the parenthesis in the docstring, PyCharm was expecting model to be a Tuple(str, Equation).
Removal of the said parenthesis resolves the issue.
> change docstring of NeuronGroup so that model isn't a tuple

- brian2/codegen/cpp_prefs.py
Try opening flag_file with encoding. As opposed to json.load. Was breaking for Python 3.9
> Fix flag_file load encoding error for Python 3.9

- brian2/codegen/runtime/cython_rt/templates/common_group.pyx
- brian2/codegen/runtime/cython_rt/templates/synapses_create_generator.pyx
- brian2/codegen/runtime/numpy_rt/templates/synapses_create_generator.py_
- brian2/core/base.py
- brian2/core/core_preferences.py
- brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp
- brian2/synapses/synapses.py
- brian2/tests/test_synapses.py
- docs_sphinx/user/synapses.rst
This will fix #664 by finally implementing the `sample(..., size=...)` syntax in synapse generators.
This basically works already, but I'm still marking this as a draft because there are a couple of open questions:
1. how do we handle various types of errors? For example, if you ask for a bigger size than possible, should this raise an error? Or should we handle this via the `skip_if_invalid` option, i.e. silently generate fewer samples than the requested `size`?
2. The current algorithm is probably inefficient for small sizes (it scales with the total number of post-synaptic neurons) which are probably a quite common use case. Maybe it would make sense to use a simple "draw `size` random numbers and re-draw numbers for non-unique items" in these cases but we should probably run some …
> Fixed size synapses

- .github/workflows/publish_to_pypi.yml
- README.rst
- azure-pipelines.yml
- brian2/codegen/cpp_prefs.py
- brian2/tests/test_codegen.py
- dev/conda-recipe/meta.yaml
- setup.py
This updates the requirements to numpy >=1.17 and Python >= 3.7 in line with the [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) guidelines. It also updates the testing to do more thorough testing on the oldest and newest supported Python version (i.e. 3.7 and 3.9) and it adds a test for issue #1284.
> Update python support

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
As @romainbrette noticed, the string representation of some units were not correct in the sense that evaluating them in Python did not result in the same unit – this is obviously bad, in particular when storing units/equations in text and importing them later (as Romain did). The problem concerned units raised to powers more than once, e.g.:
```pycon
>>> (second ** 2) ** -1  # or 1/second**2 which will be interpreted in the same way
second ** 2 ** -1
```
Due to Python's operator precedence, this will be interpreted as `second ** (2 ** -1)`, i.e. `second ** 0.5` instead of `second ** -2` as it should be. The simple fix in this PR is to consider units raised to powers as "compound units", which will lead to the use of parentheses:
```pycon
>>> (second ** 2) ** -1
(second ** 2) ** -1
``` …
> Fix unit string representation

- brian2/equations/equations.py
- brian2/tests/test_neurongroup.py
Fixes #1296 (see issue for an example of what goes wrong)
Since sympy 1.7, `sympy.latex('...')` will no longer consider a string as "already LaTeX" but rather replace backslashes in it by `\textbackslash` to make it appear as written. With this change, we now only call `sympy.latex` on sympy objects (e.g. Symbol) or our own objects implementing `_latex`.
> Fix LaTeX output for newer sympy versions

- brian2/codegen/runtime/cython_rt/templates/synapses_create_generator.pyx
- brian2/codegen/runtime/numpy_rt/templates/synapses_create_generator.py_
- brian2/devices/cpp_standalone/templates/synapses_create_generator.cpp
- brian2/synapses/parse_synaptic_generator_syntax.py
- brian2/synapses/synapses.py
- brian2/tests/test_subgroup.py
- brian2/tests/test_synapses.py
- docs_sphinx/user/synapses.rst
As briefly discussed in #1280 , the main interest of "random fixed size sampling" is typically used to have a fixed number of *inputs* per target neuron. In contrast, our current code only allows its use in `j='...'` expressions, i.e. sampling a post-synaptic neurons for each pre-synaptic neurons.
This PR adds the missing feature of also using `i='...'` generator expressions, which together with the previous changes finally makes a fixed number of incoming connections possible. The implementation is rather straightforward: it replaces hardcoded names like `j` and `post_idx` in the templates by placeholders that get filled in depending on the way we iterate. Still, everything gets a bit more complicated... I tried to at least refactor `Synapses.connect` a bit which had a really …
> Synapse generator expressions i='...'

- examples/advanced/modelfitting_sbi.py
This adds a new example demonstrating the use of the [sbi](https://www.mackelab.org/sbi/) package with Brian. Developed together with @ybernaerts and @michaeldeistler and very similar to the [Hodgkin-Huxley tutorial](https://www.mackelab.org/sbi/examples/00_HH_simulator/) in the `sbi` documentation – except for using Brian to do the simulation :)
Note that this is a bit of a bare-bones example with not much explanation. I'll convert the more detailed notebook version into a blog post for our website soon.
> Simulation-based inference example

- brian2/devices/cpp_standalone/templates/makefile
Disclaimer 1: I'm no expert on make, I just had to fix a local linking error because my system compiler was mixed with the conda environment's standard library and want to contribute this.
Disclaimer 2: I haven't tested this particular change, but I made the same edits to a makefile of an already generated standalone build and it worked there. Relying on continuous integration here :)
From the commit message:
(Ana)conda environments allow to install gcc/g++ compilers and standard libraries.
The compilers are not linked to `gcc` or `g++` but rather preserve their platform dependent naming.
For automatic compiler detection by tools conda sets environment variables.
Details: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#using-the-compiler-packages
The …
> Fix automatic g++ compiler detection on linux

- README.rst
Ah, didn't know I could edit the README on the GitHub and it would automatically create a PR!
Closes #1306
> Fix broken Contributor Convenant link on README

- brian2/parsing/bast.py
- brian2/tests/test_GSL.py
- brian2/tests/test_functions.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_poissongroup.py
- brian2/tests/test_poissoninput.py
- brian2/tests/test_refractory.py
- brian2/tests/test_spikegenerator.py
- brian2/tests/test_stateupdaters.py
- brian2/tests/test_synapses.py
- brian2/tests/utils.py
In contrast to what I claimed in #1196, the `ExceptionInfo.errisinstance` check does not actually work with chained exceptions.
Something like
```Python
assert exc_info.errisinstance(exc, KeyError)
```
will fail if exc_info is a `BrianObjectException` caused by a `KeyError`.
We have plenty of tests written like this
```Python
with pytest.raises(BrianObjectException) as exc:
net.run(0*ms)
assert exc.errisinstance(UnsupportedEquationsException)
```
These tests run just fine, but only because the test leaves the `pytest.raises` context as soon as an exception is raised, i.e. the `assert` is never triggered. This is mentioned in the [pytest documentation](https://docs.pytest.org/en/6.2.x/reference.html#pytest.raises)...
This PR fixes this by introducing our own testing function which recurses …
> Fix for exc.errisinstance with pytest.raises

- .github/workflows/testsuite.yml
Small change to use the github action I created in https://github.com/mstimberg/github-calc-nep29 (still needs to be properly documented...). Instead of hardcoding the Python versions we support, it calculates them according to [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
> Use github-calc-nep29 action instead of hardcoding Python versions

- docs_sphinx/advanced/preferences.rst
The preference `codegen.c.compiler` does not exist, guess it was renamed to `codegen.cpp.compiler`?
> Fix wrong preference example in documentation

- brian2/codegen/cpp_prefs.py
See #1322
I expected to be able to set the actual compiler binary with this preferences (which is not the case). So I added a sentence on how to set a specific compiler binary (using environment variable `CXX`). But if you think this doesn't belong here, feel free to remove it again.
And I never used Windows makefiles so I couldn't tell from the win_makefile template if there was a Windows equivalent?
> Update documentation for C++ compiler prefs

- brian2/codegen/runtime/cython_rt/templates/common_group.pyx
- brian2/codegen/runtime/cython_rt/templates/threshold.pyx
- brian2/codegen/runtime/numpy_rt/templates/threshold.py_
- brian2/core/magic.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/devices/cpp_standalone/templates/threshold.cpp
- brian2/tests/test_network.py
This fixes #1319 (a group continues to spike after it is deactivated with `active=False`). The reason was quite easy to identify: the threshold notes the spikes in the `spikespace` data structure at every time step, but it never clears it up. So if it has spiked in the last time step of a previous run, deactivating it will simply mean that the `spikespace` never gets cleared, and the object therefore repeats the spikes every time step. 
The fix is relatively straightforward: I added a cleanup step (setting the number of spikes to 0) to the `after_run` part of the thresholder template. Unfortunately, this did not work quite flawlessly, which maybe shouldn't come as a complete surprise since we've never actually used the `after_run` slots (we only needed `before_run` so far)... In …
> Fix deactivation of spiking objects

- brian2/conftest.py
The standalone project directory is not deleted for failed tests. This commit adds a section to the pytest error report that prints this directory. Helps with debugging.
This checks first if the project directory is even set, which is not the case for RuntimeDevices and standalone tests that failed before code generation. I first considered checking the test markers to decide when to print this information, but I guess checking for `project_dir is not None` is the easiest?
> Add standalone project directory path to pytest report

- brian2/core/preferences.py
- brian2/tests/__init__.py
- brian2/tests/test_preferences.py
I modified the `test_globalprefences` test to test `prefs.reset_to_defaults()`.
The function call resulted in a `TypeError` due to using `BytesIO` (change introduced in 01050fc0c). Changed it back to `StringIO`, which fixes it.
Not sure if this is an issue specific to the Python version, but the test suite will show I guess. I was running with Python 3.9.6.
EDIT:
The `TypeError` was the following:
```
Traceback (most recent call last):
File "<string>", line 13, in <module>
File "/path/to/brian2cuda/tests/features/cuda_configuration.py", line 308, in before_run
brian2.prefs.reset_to_defaults()
File "/path/to/brian2/brian2/core/preferences.py", line 460, in reset_to_defaults
self.read_preference_file(BytesIO(self.defaults_as_file))
TypeError: a bytes-like object is required, not 'str'
```
> Fix `prefs.reset_to_defaults()` which is currently failing with `TypeError`

- tutorials/1-intro-to-brian-neurons.ipynb
With the current version "Brian2==2.4.2", the last cell doesn't properly execute, as weights now has to have the same shape as x, which it can only have if it's an np array.
> Remove erroneous list operation

- brian2/codegen/cpp_prefs.py
- brian2/tests/test_codegen.py
Actually compiling the file is not only unnecessary, it also creates a spurious `-.o` file
Fixes #1348
> Use the pre-processor only when checking for C99 compatibility

- brian2/parsing/bast.py
- brian2/tests/test_neurongroup.py
Note that we actually originally planned to remove this warning when going Python2-only :)
https://github.com/brian-team/brian2/pull/984#issuecomment-409170575
Fixes #1339
> Remove warning that dividing integers leads to floating point values

- brian2/codegen/cpp_prefs.py
- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/devices/cpp_standalone/device.py
See discussion in #1333. The `sys.prefix` setting was prepended to the preferences for `include_dirs`/`library_dirs`/`runtime_library_dirs` in standalone mode, but appended in Cython (and `runtime_library_dirs` was completely ignored in Cython).
This is now uniform, the `sys,prefix` setting is simply the default for the respective preference, so the user can overwrite it completely if they prefer.
> Compiler dirs prefix

- brian2/codegen/runtime/cython_rt/cython_rt.py
- brian2/codegen/runtime/cython_rt/extension_manager.py
- brian2/tests/test_codegen.py
Mentions the `CC` and `CXX` environment variables if the Cython test compilation fails. See this discussion in the [discussion forum](https://brian.discourse.group/t/problem-with-cython) for some context.
> Helpful compile error on Unix

- brian2/devices/device.py
IDEs (e.g. the PyDev console used in PyCharm) sometimes access this to check whether an object is "array-like", to display its
shape in a variable explorer or similar mechanisms. This leads to curious warnings when importing Brian.
> Do not raise a warning when device.shape is accessed

- .github/workflows/publish_to_pypi.yml
- docs_sphinx/introduction/release_notes.rst
Make sure that we can build wheels for Python 3.10
> Update wheel building infrastructure

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
The big string formatting unification in d3ae59251c753ae introduced a regression in a few places, because the default formatting for quantities used in f-strings or `.format` is to display it as a floating point number, discarding its units:
```pycon
>>> start = 0*second
>>> duration = 1 * second
>>> print("Starting simulation at t=%s for a duration of %s" % (start, duration))
Starting simulation at t=0. s for a duration of 1. s
>>> print(f"Starting simulation at t={start} for a duration of {duration}")
Starting simulation at t=0.0 for a duration of 1.0
```
In most places, I worked around this by using something like `"... t={start!s}"` to manually force a conversion to a string, but I think it would be better if we changed quantities' default for "formatting without format spec" (which …
> Avoid that formatted strings discard units of quantities

- brian2/input/spikegeneratorgroup.py
- brian2/monitors/statemonitor.py
- brian2/tests/test_monitor.py
This bug was introduced in 9e862585 and caused string representations of StateMonitors (and Networks containing them, consequently) to fail.
> Fixed missing return in StateMonitor.__repr__

- brian2/core/names.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/tests/test_network.py
We've been discussing the issue of auto-generated names (`neurongroup_1`, etc.) in code for a while, see e.g. #680. This is a big issue without an easy fix, but when discussing a related issue in Brian2GeNN with @kernfel (brian-team/brian2genn#141) I realized that we should at least make an intermediate solution work: if the user specifies names, then the network should have consistent names for all objects. This sounds trivial, but did actually not work correctly before. E.g. when you do:
```Python
for _ in range(2):
group = NeuronGroup(10, 'dv/dt = 100*Hz : 1',
threshold='v > 1', reset='v = 0', name='group')
from brian2.core.network import _get_all_objects
print(sorted([o.name for o in _get_all_objects(collect())]))
```
You'll get:
```
['group', 'group_resetter', 'group_stateupdater', …
```
> Consistent naming for contained objects

- brian2/codegen/optimisation.py
This function is used during code optimization to replace constant expressions. It previously failed for expressions like 1/0.
This has been reported on the [discussion forum](https://brian.discourse.group/t/model-fitting-with-refractory-period/615) in the context of a model with refractoriness. With the `(unless refractory)` flag, a differential equation will be multiplied with `int(not_refractory)` and our optimization procedure recognizes this pattern and transforms it into an `if not_refractory:... else: ...` structure with 1 or 0 substituted for `int(not_refractory)`. For the refractory block, it can happen that the 0 values appears in multiple places, including the denominator of divisions – in the end this won't matter since everything gets multiplied by 0 anyway, but intermediate …
> Make evaluate_expr more robust

- brian2/monitors/spikemonitor.py
The descriptive part of the docstrings of the `EventMonitor.event_trains` and `SpikeMonitor.spike_trains` methods wrongly indicated that a dictionary mapping _event_/_spike_ indices to event/spike times is returned. What is actually returned instead is a dictionary mapping _neuron_ indices to event/spike times. This commit fixes these mistakes by changing "_event_/_spike_ indices" to "_neuron_ indices".
> Fix docstrings of `event_trains` and `spike_trains`

- brian2/devices/cpp_standalone/device.py
- docs_sphinx/user/computation.rst
I used these for my benchmarks, would like to get this out of the patch file, also for future benchmarking. Any objections? :)
> Add `before_run` & `after_run` code slots for `insert_code` mechanism

- brian2/spatialneuron/spatialneuron.py
- brian2/tests/test_spatialneuron.py
As @romainbrette noticed, the `threshold_location` argument of `SpatialNeuron` did not accept a morphology, as in 
```Python
neuron = SpatialNeuron(..., threshold_location=morpho.axon[15*um])
```
We explicitly mention this syntax in the [documentation](https://brian2.readthedocs.io/en/stable/user/multicompartmental.html#detecting-spikes), so it should work.
The workaround was to either directly provide the compartment number or use `morpho.axon.indices[15*um]`.
This PR fixes the issue, and also adds a corresponding test to make sure this error does not come up again.
> Fix using indexed morphology for threshold_location

- brian2/devices/cpp_standalone/brianlib/clocks.h
- brian2/tests/test_network.py
Before, long runs with more than 2e9 timesteps failed to run.
Note that the issue was also fixed as part of the open PR #1057, but progress on that PR has stalled.
Fixes #1394
> Avoid casting timesteps to 32bit in C++ standalone

- docs_sphinx/user/synapses.rst
> Add comment that x and y are user-defined parameters

- docs_sphinx/user/refractoriness.rst
NeuronGroup(1, model='''refractory : second''', refractory='refractory')
yields:
SyntaxError: The name 'refractory' is used in the refractory mechanism  and should not be used as a variable name.
But
G = NeuronGroup(1, model='''ref : second''', refractory='ref')
works.
> Fix documentation wrt. refractory period as variable

- brian2/codegen/codeobject.py
- brian2/codegen/generators/cpp_generator.py
- brian2/codegen/generators/cython_generator.py
- brian2/devices/cpp_standalone/device.py
- brian2/monitors/spikemonitor.py
Two main issues led to code files changing for identical models (i.e., even when running a model again in a new process where the problems with regard to names as discussed in #680 do not play a role):
1. Variable declarations and other "unordered" code was generated in a different order for every run, and
2. The file names written to the result directory used `hash()` to deal with the problem of case-insensitivity on Windows (otherwise `i` and `I` would be stored to the same file). For security reasons, the `hash()` function changes its output for every run.
The fix in this PR is to:
1. Use `sorted()` whenever iterating over variables that are stored in sets, and 
2. Use `zlib.crc32` instead of `hash` to calculate the hash value for the filenames. Strictly speaking, `crc32` is a checksum …
> Deterministic code generation

- brian2/codegen/cpp_prefs.py
Somewhat similar to #1348, our check whether the compiler supports certain flags created the compiled object files in a `tmp` directory in the current directory. This PR:
1. Creates these files in the temporary directory instead, and
2. Removes them after compilation
> Avoid creating temp files in current dir

- brian2/devices/cpp_standalone/device.py
I used these for benchmarks as well. I find this information quite useful. I would even go as far as printing it out explicitly when running with `profile=True`. Or even when not running with it. At least for Brian2CUDA this could be quite important to evaluate the usefulness of using a GPU or not. Or to track down why things go slow.
I just copied what I used in the patch file. It adds a bit of noise to the code and it adds the overhead of 4 `time.time()` calls. If you want, I can make this optional, only when `profile == True` or anything like that? But I doubt this generates much simulation overhead, no?
Oh, and I only added it to the CPPStandaloneDevice I just realized. If you want this, I can also add it to the other devices of course?
> Add timers for compilation and binary execution

- brian2/core/variables.py
These are used when handing a `VariableView` directly to matplotlib, e.g. for `spike_mon.i` (an expression like `spike_mon.t/ms` directly results in an `ndarray` and is therefore not concerned). This problem was introduced with matplotlib 3.5.2, previous versions converted `VariableView` along the way with a call to `np.asanyarray`.
The fix is a minimal workaround, but we have plenty of examples, including the tutorials, that will fail plotting, so fixing this is urgent. For a proper fix I'd like to think a bit more about how (and whether) to support features like adding array dimensions, in particular for synaptic variables which support a form of 2d-indexing which is not the same as for a 2d `ndarray`.
Fixes #1409
> Handle .ndim and [:, np.newaxis] on VariableView

- brian2/tests/test_logger.py
- brian2/utils/logger.py
- dev/continuous-integration/run_simple_test.py
- dev/continuous-integration/run_test_suite.py
- docs_sphinx/advanced/logging.rst
See the discussion in #1418. This PR changes the default file log level to DEBUG, switches off file logging when the logger is accessed from a process different from the one that called `BrianLogger.initialize()`, and updated the documentation accordingly.
@schmitts & @thesamovar, let me know if anything is unclear or could be improved.
Fixes #1418
> Logging with multiprocessing

- brian2/core/variables.py
Yet another fix for #1409, needed when e.g. plotting spikes from a
subgroup.
> Fixes indexing VariableViews with [:, np.newaxis] for subgroups

- brian2/codegen/runtime/cython_rt/templates/common_group.pyx
- brian2/tests/test_spatialneuron.py
Support code has to be included for `before_run` blocks, otherwise variables needed for functions that refer to namespaces (e.g. `TimedArray`) will not be correctly defined. This is a simple fix, in the longer run we should think about custom functions, namespaces etc. in `before_run` block. Currently, these blocks do not actually need any of all this, since they don't run user-defined code (but potentially that might change in the future?).
Fixes #1427, see https://brian.discourse.group/t/time-dependend-input-in-equation-vs-parameter/753/5 for example code that failed previously.
> Cython: Include support code in before_run block

- brian2/devices/cpp_standalone/templates/common_group.cpp
- brian2/tests/test_cpp_standalone.py
The `after_run` and `before_run` code blocks (only used in a few templates) were including support code, but not user-provided header files. This means that user-defined functions that relied on external header files were not compiling correctly. The fix is rather trivial and has considerably fewer lines of code than the new test :blush: 
See https://brian.discourse.group/t/how-to-use-prefs-devices-cpp-standalone-extra-make-args-unix/783 for the discussion that triggered this PR (and thanks to @wxie2013 for reporting it!).
> include user headers in before/after blocks

- brian2/tests/test_units.py
- brian2/units/fundamentalunits.py
Fixes the issue reported by @appukuttan-shailesh in #1431: for efficiency reasons, we compare `Dimension` objects with `is`, which generally works since they are singletons. They are never created directly, but always via `get_or_create_Dimension` which will return a reference to a previously existing `Dimension` object if they are the same.
This was broken during pickling, since the unpickled object was no longer identical to the previous singleton. As described by @appukuttan-shailesh in #1431, this can lead to weird error messages like 
Expression 'v - vr' uses inconsistent units ('v' has unit V; 'vr' has unit V).
with both variables referring to separate instances of a `Dimension` object for volt. The fix is quite straightforward with Python's `__reduce__` mechanism; `Dimension` …
> Dimension objects should stay singletons even when pickled

- brian2/__init__.py
Replace distutils.version.LooseVersion with packaging.version.Version.
> Replace deprecated distutils package

- .github/workflows/testsuite.yml
- brian2/sphinxext/generate_examples.py
In [Debian Bug#1027936], Adrian Bunk noticed that the documentation failed to be produced with python3.11 with the following symptom:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/sphinx/config.py", line 350, in eval_config_file
exec(code, namespace)
File "/<<PKGBUILDDIR>>/docs_sphinx/conf.py", line 71, in <module>
generate_examples.main(root_dir, target_dir)
File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.11/dist-packages/brian2/sphinxext/generate_examples.py", line 72, in main
with codecs.open(fname, 'rU', encoding='utf-8') as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen codecs>", line 906, in open
ValueError: invalid mode: 'rUb'
This patch removes a couple of uses of unified newline "open" invocations, which have no effect since the first …
> Failure to produce documentation with python3.11.

- versions.md
In response to the discussion about synchronising package versions across the whole project (https://github.com/brian-team/brian2/pull/1449#issuecomment-1372476018), as an interim measure, this is a manually curated list of files which contain package versions, enabling us to check them and update as necessary when updating a dependency.
> Create list of package versions

- brian2/tests/test_logger.py
- brian2/utils/logger.py
Makes non-ASCII characters in log messages work on Windows.
See https://brian.discourse.group/t/logging-error-on-windows/872/3
> Force UTF-8 encoding for file logs

- brian2/tests/test_stateupdaters.py
Cython 3.0 fails doing a type case otherwise
> Small changes for two tests to use floats

- brian2/codegen/generators/base.py
- brian2/codegen/generators/numpy_generator.py
- brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
- brian2/spatialneuron/spatialneuron.py
- brian2/tests/test_spatialneuron.py
Running `SpatialNeuron` with `numpy` now requires the `scipy` package – the previous "pure-numpy" fallback has been removed. It was broken and complicated the code in general; as discussed in #1459, `scipy` is a standard dependency and maintaining an alternative, scipy-independent approach seems unnecessary.
Closes #1459
> Remove numpy-fallback for SpatialNeuron

- .github/workflows/publish_to_pypi.yml
This builds binary wheels for the `linux-aarch64` architecture (emulated via `qemu`, all the difficult parts are handled by [`cibuildwheel`](https://cibuildwheel.readthedocs.io/) luckily…).
@bdevans made me aware that this architecture (Linux on ARM64 hardware) is not as niche as I had previously assumed: running Linux on newer Apple hardware (e.g. via docker) will require it.
When this is merged into master, packages will appear on https://test.pypi.org/project/Brian2/, and can be installed as explained here: https://brian2.readthedocs.io/en/stable/introduction/install.html#development-install
> Build wheels for linux-aarch64

- brian2/codegen/generators/GSL_generator.py
Fixes an incompatibility with latest Cython beta, related to exception
handling (which is automatically switched off if a function is marked
as extern)
Fixes #1470
> Mark GSL functions as extern

- brian2/codegen/generators/GSL_generator.py
- brian2/codegen/optimisation.py
- brian2/core/variables.py
- brian2/groups/group.py
- brian2/monitors/spikemonitor.py
- brian2/synapses/synapses.py
- brian2/units/fundamentalunits.py
This fixes a number of issues that will raise warnings in the forthcoming numpy version (1.25).
> Fix numpy warnings

- .readthedocs.yaml
As @kernfel noticed, our documentation wasn't including the tutorials anymore. In addition, the examples were included without their plots. The reason was simply that readthedocs wasn't checking out the `docs_sphinx/resources` submodule, this should be fixed with this change to the rtd configuration file.
Closes #1477
> Check out submodules to correctly build example/tutorial docs

- brian2/utils/logger.py
- docs_sphinx/developer/guidelines/logging.rst
Brian configures the logging infrastructure under the `brian2` logger root, so all uses of the logger need to have a `brian2.something` name.  This leads extension packages like `brian2cuda` to use names that do not correspond to actual module names, e.g.:
https://github.com/brian-team/brian2cuda/blob/f240d34c45daa858716da9176936cd642f17ccb2/brian2cuda/cuda_generator.py#L24C1-L24C64
This can be potentially confusing for users, but also for the test suite: in several places the test suite checks for specific warnings (or the absence of such warnings). If `brian2cuda` logs a warning in one of those tests, the test will fail even though the warning is not relevant to the test.
With this PR, packages can use Brian's logger with `get_logger` using their own name (typically …
> Better logging for extension modules

- .github/workflows/test_latest.yml
Update our `test_latest` workflow so that we can already test against Python 3.12 pre-releases (release expected in October).
> Test against python312

- brian2/codegen/optimisation.py
- brian2/parsing/bast.py
- brian2/parsing/expressions.py
- brian2/parsing/rendering.py
This removes references to deprecated classes/attributes of Python's `ast` module (which raise warnings with Python 3.12 and will be removed in 3.14). It also removes alternative code paths that were necessary for backwards compatibility with Python ≤3.7.
> AST deprecation fixes

- .github/workflows/test_latest.yml
- README.rst
- brian2/core/variables.py
- brian2/groups/neurongroup.py
- brian2/units/fundamentalunits.py
- dev/continuous-integration/run_test_suite.py
- pyproject.toml
This fixes a few issues for compatibility with the upcoming (backwards-compatibililty breaking) 2.0 version of numpy. It also switches off the GSL tests for now – GSL is broken on C++ standalone for unrelated reasons (and by chance/bad luck, the way it broke made it skip the tests so I only realized recently…). 
I still need to check whether any of the changes requires us to update our minimum version requirement for numpy, but I don't think it is.
> Numpy 2 compatibility

- examples/frompapers/Izhikevich_2007.py
This pr is regarding issue [#1476](https://github.com/brian-team/brian2/issues/1476) .I have updated the formula for Izhikevich_2007 example neuron model. Let me know if any other changes are required to be made. (This is my first contribution to brian and open source , apologies for any mistake made from my end). Thanks
> Formula update for Izhikevich_2007 Example

- examples/frompapers/Wang_2002.py
This is a reasonably fast implementation of Wang (2002), Probabilistic Decision Making by Slow Reverberation in Cortical Circuits, which many people are interested in (see e.g. [this discussion on the forum](https://brian.discourse.group/t/reproducing-probabilistic-decision-making-by-slow-reverberation-in-cortical-circuits-2002-by-x-j-wang). This example is particularly interesting, because the most straightforward implementation of the NMDA synapses – ignoring the special all-to-all connectivity structure with identical weights within subpopulations – will be *very* slow.
Actually, optimizing this model (which was mostly written by @wklausito) made me realize that for a model like this, C++ standalone now spends most of its time in creating random numbers (#1483). In C++ standalone, we …
> Add Wang 2002 example

- .github/workflows/test_latest.yml
- dev/continuous-integration/run_test_suite.py
We run tests against the latest versions of numpy, etc. (including pre-releases) every week. Currently, these tests fail even if they just raise deprecation warnings. I separated out these tests and no longer mark them as failed – we still have the log output if we want to check manually.
In the long run, we could maybe have the GitHub action post the results about deprecation warnings to an issue as a comment.
> Separate the tests for deprecation warnings

- MANIFEST.in
- pyproject.toml
I'm going to preface this PR by saying that I do not know why the current upstream configuration works. From what I see in the various docs, it shouldn't, but there's so much going on in the Python packaging ecosystem that I'm no longer confident I understand it all properly :joy: 
While building on Fedora, the current pyproject.toml etc., doesn't work---it only includes the top level brian2 package in the generated wheels. This seems to be the correct behaviour because as the setuptools documentation notes (or suggests rather), only including the top level package name in the package list is not enough. One either has to list all sub-packages, or use the discovery tools.
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#package-discovery-and-namespace-packages
So, to …
> Setuptools related improvements

- LICENSE
- brian2/codegen/generators/cpp_generator.py
- brian2/tests/test_neurongroup.py
This fixes #1495. As mentioned in the issue, the problem is that we use `floor(1.0*x/y)` to calculate floor division with Python semantics in C++. By default, we have unsafe math optimizations enabled, which leads to this not always being correct (e.g. 98/98 would be rounded down to 0). I think this is due to replacing the division by multiplication with an approximated reciprocal, or something along these lines. Switching off unsafe optimizations would be an option, but it would slow down code in other places.
In this PR, I instead create function specializations for integer arguments, which then use a rather complex calculation to get the value:
```c++
q = a / b;
r = a - q*b;
q -= ((r != 0) & ((r ^ b) < 0));  // result
```
This is the implementation used by Cython (`cdivision: false`, …
> Correct C++ floor division for integers

- brian2/codegen/cpp_prefs.py
This patch extends the just-in-time compiler options in brian2/codegen/cpp_prefs.py to optimize aggressively on loongarch64 CPU, similarly to numerous other platforms already supported by brian2.
It was originally published in [Debian bug #1059428] and provided by Loongson.
[Debian bug #1059428]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1059428
> Extend compiler cpu optmizations to loongarch64.

- README.rst
- docs_sphinx/conf.py
- docs_sphinx/developer/standalone.rst
- examples/frompapers/Naud_et_al_2008_adex_firing_patterns.py
- pyproject.toml
- rtd-requirements.txt
Builds on readthedocs were failing due to a dependency conflict – we were requiring a very old version of Sphinx, this PR updates the dependency to Sphinx >= 7 (latest major version).
> Sphinx update

- .github/workflows/publish_to_pypi.yml
- .github/workflows/test_latest.yml
- .github/workflows/testsuite.yml
This PR enables the new [M1 runners for open source projects](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/), i.e. we can now test and build packages on Apple M1 hardware. We've already built packages for `macos-arm64` via cross-compilation before, but we couldn't test them. This PR also updates the workflows in a few other minor ways.
> Enable M1 runner on workflows

- brian2/codegen/runtime/cython_rt/templates/common_group.pyx
- brian2/tests/test_functions.py
Avoids that `x**y` becomes a float for two integers, leading to compilation errors. This behaviour changed with Cython 3.0. While I think there's a point for having `x**y` only being an integer if the compiler knows that `y` is non-negative, in practice I don't think there is much use of this kind of exponentiation outside of expressions such as `(-1)**k`. Whatever we'd decide for this in the long run, right now this fix assures that there is no difference depending on your version of Cython.
Fixes #1500
> Use `cpow=True` in Python

- docs_sphinx/user/recording.rst
- docs_sphinx/user/synapses.rst
Hi, following our discussion [here](https://brian.discourse.group/t/how-to-implement-a-populationstatemonitor/1138), I added a small section to the documentation that outlines how to continuously record population averages in a memory efficient way (so I can find the information next time I need it). 
The section is based on the example given by @mstimberg [here](https://brian.discourse.group/t/is-there-a-way-to-monitor-the-average-membrane-potential-of-a-group-of-neurons/658/3).
```python
group = NeuronGroup(..., 'dv/dt = ...', ...)
vm_container = NeuronGroup(1, 'average_vm : volt')
vm_averager = Synapses(group, average_vm, 'average_vm_post = v_pre/N_pre : volt (summed)')
vm_averager.connect()
vm_mon = StateMonitor(vm_container, 'average_vm', record=0)
```
I made the following changes: …
> Document how to record population averages in a memory efficient way

- .github/workflows/test_latest.yml
- brian2/core/variables.py
- brian2/numpy_.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_units.py
- brian2/tests/utils.py
- brian2/units/fundamentalunits.py
Various fixes for to make the unit system compatible with the upcoming numpy 2.0 release. It might make sense to revisit this more fundamentally at a later point, but for now the main change is that `__array_wrap__` and `__array_prepare__` are merged into `__array_ufunc__`. Without doing anything further, this actually enables some new functionality like:
Before:
```
>>> np.add.reduce(np.arange(3)*mV)
Quantity(0.003)
```
After:
```
>>> np.add.reduce(np.arange(3)*mV)
3*mV
```
But I don't think many users do complex calculations with `Quantity` arrays in the first place. Still, we need to point this out clearly in the release notes, it might break some code. As discussed, the changes in numpy's system also lead to things like `x**(2*volt)` no longer raising an error, since `float(2*volt) == …
> Numpy2 compatibility (brian2.units)

- .github/workflows/test_latest.yml
- brian2/core/network.py
- brian2/core/variables.py
- brian2/monitors/spikemonitor.py
- brian2/units/fundamentalunits.py
- brian2/units/unitsafefunctions.py
- numpy2.pyproject.toml
In numpy 1.x, `array(x, copy=False)` meant : do not copy if possible. In numpy 2.0, it will raise an error if copying is not possible. This commit replaces the use of `array(x, copy=False)` by `asarray(x)`, which has the "do not copy if possible" in both numpy 1.x and numpy 2.0.
> New array copy semantics

- brian2/tests/test_logger.py
- brian2/utils/logger.py
catch_logs was supposed to ignore warnings not coming from brian2, but
it included messages from loggers whose names *start* with "brian2",
including "brian2cuda"…
> Fix catch_logs behaviour for 3rd-party modules

- dev/continuous-integration/run_test_suite.py
These were switched off due to some installation issues on the test servers, but now everything seems to work smoothly.
> run GSL tests

- brian2/parsing/rendering.py
Usually, this shouldn't be a problem (implicit type cast), but it is at least surprising and may also break tests assuming that the numbers appear in the code.
> Number 0 and 1 were rendered as false and true in C++ code

- .github/workflows/test_latest.yml
- brian2/codegen/runtime/GSLcython_rt/GSLcython_rt.py
- dev/continuous-integration/run_test_suite.py
On `test_latest.yml`, we use Microsoft's `vcpkg` manager to install the GSL for all operating systems. Until recently (see #1523), we weren't actually running the GSL tests, so it went unnoticed that this doesn't quite work. In contrast to the installation of GSL via `conda`, we need to manually set the path with the `GSL.directory` preference. During fixing this, I also realized that our current GSL code did only use this preference for the include path with isn't enough, we only need it for the library path (and the DLL path on Windows).
These tests show that it now runs correctly: https://github.com/brian-team/brian2/actions/runs/8706379543
(The checks in this PR only show that it didn't break anything for code that doesn't need the `GSL.directory` preference).
> Fix GSL to work with vcpkg installation (used in test_latest.yml)

- .github/workflows/test_latest.yml
- .github/workflows/testsuite.yml
This PR enables caching the Cython cache directory on GitHub actions. For repeated CI runs on the same branch (assuming no major changes that affect the generated Cython code), this greatly reduces the time for the test suite to run through (from about 1h15 to 0h30).
> Cache cython on CI

- brian2/devices/cpp_standalone/templates/objects.cpp
- brian2/tests/test_cpp_standalone.py
This broke setting values with arrays for group names with upper case characters.
This issue was reported by `DavidKing2020` on the [Brian discussion forum](https://brian.discourse.group/t/cant-modify-synaptic-group-attribute-using-run-args-in-standalone-mode/1219/8).
> Do not convert run_args values to lower case

- brian2/sphinxext/docscrape.py
- brian2/sphinxext/examplefinder.py
- dev/tools/docs/build_html_brian2.py
- dev/tools/docs/quick_rebuild_html_brian2.py
When fixing warnings about unused variables and similar issues quite a while back (commit 0344b00), I inadvertently broke a few features of the reference documentation – partly because some of the warnings were somewhat misleading (e.g. some function call return values weren't used, but the functions updated global variables). This should fix the issue dicussed in #1532. 
I've built the updated documentation here, from a quick glance it seems to be working correctly: https://brian2.readthedocs.io/en/fix_doc_reference_issues/
Closes #1532
> Fix reference doc issues

- examples/frompapers/Brunel_Wang_2001.py
Deleted "eqs_pre_ext" in rhe Brunel-Wang 2001 example implementation.
These equations aren't used anywhere in the simulation. 
Their inclusion is likely an oversight. 
Removed to make the code more clear.
> Fix Error in Brunel_Wang_2001.py

- brian2/__init__.py
- brian2/core/base.py
- brian2/core/network.py
- brian2/groups/subgroup.py
- brian2/tests/test_network.py
- brian2/tests/test_neurongroup.py
- brian2/utils/logger.py
This addresses the issue in #1499, by raising a warning if an object gets garbage collected but has never been included in any `Network`. Instead of dealing with the complexities of weak references and the `InstanceTracker`, as initially proposed in #1499, this simply uses the `__del__` function in `BrianObject`. This seems to be working well, and running it against our examples I did not encounter any issues. There are false positives for "artificial" examples like https://brian2.readthedocs.io/en/stable/examples/synapses.efficient_gaussian_connectivity.html, since they create `Synapses` but do not ever run a simulation. In principle, we could have another check that only triggers these warnings when there has been a `run` at some point, but I am not sure whether it is worth the …
> Unused object warning

- .pre-commit-config.yaml
- brian2/core/functions.py
- brian2/units/fundamentalunits.py
- docs_sphinx/introduction/release_notes.rst
- pyproject.toml
Release notes for the upcoming 2.7 release (most importantly to ensure compatibility with numpy 2.0).
Also changes our pre-commit hooks to target Python >3.10
> Release notes for 2.7

- brian2/synapses/synapses.py
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/release_notes.rst
This worked previously, but was broken with commit d3d9e1684b4308fe See https://brian.discourse.group/t/how-to-activate-synaptic-pathways-on-custom-events-only/1213 and https://brian.discourse.group/t/reproducibility-issue-between-brian2-5-and-2-7/1240.
> Fix `on_event` with pathway names

- brian2/spatialneuron/morphology.py
- brian2/tests/test_morphology.py
Standardized SWC files on neuromorpho.org use the [three-point soma representation](https://neuromorpho.org/SomaFormat.html), but in practice they are usually a bit off (i.e. the two exterior points are not at exactly one radius away from the  center point). This PR makes our conversion code less strict to load these files. It also fixes an error that prevented the related error message to display correctly. Finally, the previous code used recursion even for going along chains of compartments, which could lead to `RecursionError`s for big morphologies. This has been replaced by simpler loops.
See [discussion on the Brian discourse group](https://brian.discourse.group/t/value-error-when-drawing-morphology-of-a-downloaded-spatial-neuron) for context.
> Improvements for SWC file loading

- .coveragerc
- .github/workflows/testsuite.yml
- brian2/tests/pytest.ini
- brian2/tests/test_cpp_standalone.py
- brian2/tests/test_logger.py
- brian2/utils/logger.py
- dev/continuous-integration/run_test_suite.py
- numpy2.pyproject.toml
- pyproject.toml
We previously used the separate `coverage.py` utility, which seems not to handle our somewhat convoluted `pytest` setup 100% correctly  – I did not look into it in much detail, but our coverage on coveralls clearly showed code as not covered that was covered by tests (I double-checked by raising an Exception in the "uncovered" code). Using `pytest-cov` seems to be the better solution, and while there were a few issues with multiprocessing (since we also run our tests in parallel), it now seems to run smoothly. Without adding a single test, our test coverage jumps from 82% to 92% :laughing:
> Move to pytest-cov

- brian2/tests/test_codegen.py
In sympy 1.13.0, symbolic representation differentiates between integers and floats.  See [sympy merge request 25614] for further details.  This results in a test case failure in test_codegen.py's test_automatic_augmented_assignments when checking that there is no formal difference between "x = x + x" and "x *= 2.0":
_____________________ test_automatic_augmented_assignments _____________________
@pytest.mark.codegen_independent
def test_automatic_augmented_assignments():
variables = {
"x": ArrayVariable("x", owner=None, size=10, device=device),
"y": ArrayVariable("y", owner=None, size=10, device=device),
"z": ArrayVariable("y", owner=None, size=10, device=device),
"b": ArrayVariable("b", owner=None, size=10, dtype=bool, device=device),
"clip": DEFAULT_FUNCTIONS["clip"],
"inf": …
> b/t/test_codegen.py: fix 2.00000000000000 == 2

- brian2/codegen/cpp_prefs.py
- brian2/devices/cpp_standalone/device.py
This replaces `msvc.msvc14_get_vc_env` (the `msvc` module has been removed from `setuptools` in version 74), by `distutils._msvccompiler import _get_vc_env`, which appears to work as a drop-in replacement. IIUC, the `setuptools.msvc` added a bit of functionality for newer compilers compared to the support in `distutils`, but those changes have been contributed to `distutils` since. This is maybe not the cleanest solution (`_get_vc_env` is not really meant for public use), but the `distutils` infrastructure is meant to be used for building Python extension packages, not for generating code at runtime, so we'll always have to work around its limitations a bit.
Speaking of which, this PR also fixes a few issues that I noted during testing on my Windows VM, most importantly quoting …
> Setuptools compatibility and Windows fixes

- .github/workflows/publish.yml
> Publish docker images to GitHub container registry

- brian2/core/variables.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_subgroup.py
I don't know if this behavior is desired, but if it is and tests pass, this seems to work.
closes #1555
> potential VariableView.shape fix

- brian2/codegen/optimisation.py
- brian2/conftest.py
- brian2/parsing/functions.py
- brian2/parsing/rendering.py
- pyproject.toml
Nothing particular interesting here, but one doctest failed with Python 3.13 (output of `ast.dump` changed slightly). The remaining changes only prevent deprecation warnings, nothing would break yet.
> Python3.13

- .github/workflows/publish.yml
- .github/workflows/static_analysis.yml
- .github/workflows/test_latest.yml
- .github/workflows/testsuite.yml
Not that we are a high-profile project for this kind of security issues, but better be safe than sorry :-)
> GitHub Actions security

- .codemeta/codemeta_base.json
- .codemeta/create_codemeta.py
- .github/workflows/post_release_updates.yml
- dev/continuous-integration/update_zenodo_swh.py
- dev/tools/release/release.py
This PR integrates the update of a `codemeta.json` file into the release script. This file is mostly static, but needs to be updated with the contributors and the current version. The reason for this is mostly that this file is mandatory for uploading software to HAL (https://doc.hal.science/deposer/deposer-le-code-source/#sur-linterface-de-hal-cliquer-sur-longlet-depot_1), France's official pre-/post-print server that is sometimes queried to get all contributions by a researcher, etc. 
This PR also adds a GitHub action to update README file and CITATION.cff with the latest Zenodo archive and Software Heritage ID (which I regularly forgot). This action needs to be triggered manually, since it requires that the archives already exist.
> Codemeta.json and update for Zenodo/SWH identifiers

- brian2/core/variables.py
- brian2/groups/group.py
- brian2/groups/neurongroup.py
- brian2/synapses/synapses.py
- brian2/tests/test_neurongroup.py
- brian2/tests/test_synapses.py
- docs_sphinx/introduction/release_notes.rst
- docs_sphinx/user/equations.rst
- docs_sphinx/user/models.rst
- examples/synapses/homeostatic_stdp_at_inhibitory_synapes.py
Previously, "linked variables" could not be used with `Synapses`, since the dynamic number of synapses makes a static mapping fragile. With this PR, `Synapses` gains the possibility to link to scalar variables and to variables in groups of size 1, where there is no ambiguity. In addition, all groups (including `Synapses`) can link to other variables using a dedicated index variable (which could even change its values over time, which might be useful for some corner cases). Since this variable would grow together with the number of synapses, it will always be of the right size. However, note that using an index variable means that simulations can crash due to out-of-bounds access. Actually, the `linked_var` documentation already stated:
> index : str or …
> Extend linked variables functionality

- .github/workflows/publish.yml
- brian2/codegen/cpp_prefs.py
- docker/Dockerfile
Setuptools/distutils keep refactoring their package structure, meaning that our imports for the internal functions related to the MSVC environment have to be adapted.
> Fix imports for recent setuptools

- setup.py
This PR replaces distutils.errors with setuptools.errors in setup.py, future-proofing the code as distutils will eventually be removed. PlatformError is also imported as DistutilsPlatformError to maintain consistency with the original code, ensuring compatibility with future Python versions.
> Fix setup script: replace distutils.errors with setuptools.errors

- examples/network_operation_stop.py
This PR adds a simple example for `network_operation` to the `examples/` directory, as requested in #1068.
> Add network_operation example to examples/ (fixes #1068)

- .github/workflows/post_release_updates.yml
- .github/workflows/publish.yml
- .github/workflows/static_analysis.yml
- .github/workflows/test_latest.yml
- .github/workflows/testsuite.yml
To avoid excessive merges and test runs, this PR combines the recent dependabot PRs (#1610, #1611, #1612, #1613, #1614)  into a single one.
> Bump versions for GitHub actions

- .github/workflows/testsuite.yml
- brian2/codegen/cpp_prefs.py
The current C99 check hardcoded `cc` as the compiler name, which is usually available on Unix systems. In conda environments, however, compilers installed into the environment are not available under this name. Their names are made available via environment variables, though, so the updated code uses the `$CC` value first, and only uses `cc` as a fallback in case that variable is not defined. This should better match the behaviour when we actually compile things for running the simulation.
> Improve C99 check on Unix

- brian2/codegen/cpp_prefs.py
Avoids the setuptools warning with the latest version and makes it more future-proof in the sense that msvc-related import failures will only affect Windows.
> Avoid setuptools warning

- brian2/core/preferences.py
- brian2/tests/test_base.py
- brian2/tests/test_preferences.py
Two small fixes:
- More robust test for version tuple vs. version string that does not fail for development versions that end with `.postXXX`
- Raise an `AttributeError` instead of a `KeyError`, when accessing non-existing attributes of the preferences object. This prevents errors when using `hasattr` for non-existing attributes which is most likely behind the error seen on Google Collab when the Debugger is active, see https://brian.discourse.group/t/error-in-google-colab/1401
> Small fixes

- brian2/__init__.py
- brian2/core/core_preferences.py
- brian2/core/network.py
- brian2/devices/cpp_standalone/device.py
- brian2/devices/cpp_standalone/templates/main.cpp
- brian2/devices/cpp_standalone/templates/network.cpp
This interrupts a "graceful stop" if you interrupt a simulation with Ctrl+C (or e.g. use the interrupt mechanism in a Jupyter notebook). During a simulation run, pressing Ctrl+C will not trigger the usual interrupt (or `KeyboardInterrupt`), but instead do the equivalent of a `Network.stop()`, i.e. finish the current time step and then stop the simulation. This means that in particular for scripts that the code after the simulation run will still be run and can analyse/save/plot results. This works for both runtime and C++ standalone simulations.
@thesamovar @bdevans could you please test this on Windows/macOS? I'd use an example that takes a while to run, e.g. [COBAHH](https://brian2.readthedocs.io/en/stable/examples/COBAHH.html). After it shows "Starting simulation at t=0. s for a …
> Interrupt hook (graceful stop with Ctrl+C)

- brian2/codegen/runtime/cython_rt/templates/synapses.pyx
- brian2/codegen/runtime/cython_rt/templates/synapses_push_spikes.pyx
- brian2/synapses/cythonspikequeue.pyx
- brian2/synapses/synapses.py
This PR removes indirect Python method calls for interacting with the spike queue during synaptic spike propagation and replaces them with **direct C++ access** via Cython, improving runtime performance.
Previously, the `synapses_push_spikes.pyx` template (and related code objects) relied on Python methods like:
* `_owner.push_spikes()`
* `_owner._queue.peek()`
* `_owner._queue.advance()`
This created an inefficient call chain:
```
Cython → Python → C++ (via method call)
```
---
A **C++-only access path** through PyCapsules and minimal C++ interfaces:
| Operation       | Old (Python method)    | New (Direct C++ via Cython) |
| --------------- | ---------------------- | --------------------------- |
| Push spikes     | `_owner.push_spikes()` | `cpp_queue->push(...)`      |
| Peek from …
> Eliminate Python Layer Calls in `Synapses` Codegen Templates for SpikeQueue Operations

- .github/workflows/testsuite.yml
Doctest discovery is broken for wrapped C functions (e.g. from numpy). This is a regression that has been introduced with the last bugfix release of Python 3.11, and will probably not be fixed anymore in 3.11. I guess we could work around the problem in our test suite in some way, but for now we simply do not install an affected Python version during the tests. This will solve itself in April 2026 when we drop Python 3.11 support ;-)
See python/cpython#117692
> Avoid using Python version >=3.11.9 but <3.12 for tests

- brian2/devices/cpp_standalone/device.py
When using `run_args`, we go through all variables in the array cache, and check whether they should be invalidated. This can lead to a `ReferenceError` if a variable in the cache refers to an ephemeral subgroup. The fix is simply to swallow this error (but maybe these variables shouldn't be in the array cache in the first place?)
Fixes #1673
> Avoid `ReferenceError` when using `run_args`
