brian-team/brian2

brian2/codegen/runtime/cython_rt/templates/common.pyx
brian2/codegen/runtime/cython_rt/templates/spatialneuron_prepare.pyx
brian2/codegen/runtime/cython_rt/templates/spatialstateupdate.pyx
brian2/codegen/runtime/numpy_rt/templates/spatialneuron_prepare.py_
brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
brian2/codegen/runtime/weave_rt/templates/spatialneuron_prepare.cpp
brian2/codegen/runtime/weave_rt/templates/spatialstateupdate.cpp
brian2/codegen/runtime/weave_rt/weave_rt.py
brian2/core/variables.py
brian2/devices/cpp_standalone/brianlib/common_math.h
brian2/devices/cpp_standalone/device.py
brian2/devices/cpp_standalone/templates/spatialneuron_prepare.cpp
brian2/devices/cpp_standalone/templates/spatialstateupdate.cpp
brian2/groups/group.py
brian2/spatialneuron/morphology.py
brian2/spatialneuron/spatialneuron.py
brian2/tests/test_morphology.py

Not quite ready for merging yet, I sometimes get segmentation faults with Cython... @thesamovar: could you have nevertheless a look at it whether it runs under Windows? I'm quite sure I sneaked in something Linux and/or gcc-specific...
There are no more Python-only bits in the simulation of `SpatialNeuron` now, so that means we can run it under standalone (yay :-) ). There is a small bug that make some examples not work where standalone does not like assignments like `neuron.I[0] = 1*nA`, but this is not spatialneuron-specific (and can be worked around by `neuron.I = 'int(i==0)*nA'` for now).

Spatialneuron

---

LICENSE
brian2/groups/group.py
brian2/groups/poissongroup.py
brian2/groups/spikegeneratorgroup.py
brian2/spatialneuron/spatialneuron.py
brian2/synapses/synapses.py
brian2/tests/test_neurongroup.py
brian2/tests/test_utils.py
brian2/utils/stringtools.py

Ready to merge from my side, see discussion in #393.

Unknown attributes

---

brian2/core/variables.py
brian2/tests/test_synapses.py

This makes sure that all `Variable` objects, including `Constant` and `AttributeVariable` have an `owner` attribute, making it easier to check for the owner of variables in a general way. Also adds a `variables_by_owner` utility function that returns all variables that "belong" to a group:
```Python
from brian2 import *
from brian2.core.variables import variables_by_owner
S = Synapses(...)
syn_vars = variables_by_owner(S.variables, S)
pre_vars = variables_by_owner(S.variables, S.source)
```
From my side: ready-to-merge

Improve `Variable` objects

---

brian2/sphinxext/examplefinder.py

Example finder now finds tutorials as well as examples

---

brian2/tests/__init__.py
brian2/tests/test_network.py
brian2/tests/test_neurongroup.py
docs_sphinx/developer/guidelines/testing.rst

This fixes the issues that Owen mentioned on the mailing list (except for the Cython issue that we can't reproduce). Good to merge from my side.

Test suite fixes

---

brian2/devices/cpp_standalone/device.py

fixes: #356 
Suggestions for other function names, further refactoring, ... are also welcome

refactoring CPPStandaloneDevice

---

brian2/input/poissoninput.py

Pass the target group's clock to CodeRunner in PoissonInput's `__init__`.

Pass target's clock to CodeRunner in PoissonInput.

---

brian2/tests/test_units.py
brian2/units/fundamentalunits.py
docs_sphinx/user/units.rst

[MRG] Don't change the underlying value for in-place operations on scalar quantities

---

brian2/stateupdaters/explicit.py
brian2/tests/test_stateupdaters.py

Closes #477
The test is very crude, though...

[MRG] Fix multi-step state updates for non-autonomous equations

---

docs_sphinx/advanced/how_brian_works.rst

Ready to merge if the text seems good. @romainbrette - what do you think?
Fixes #444.

[MRG] Documentation for clock versus event driven simulation

---

brian2/input/binomial.py

[MRG] Make `BinomialFunction` extensible for other devices/codegen targets

---

brian2/codegen/runtime/cython_rt/templates/statemonitor.pyx
brian2/codegen/runtime/weave_rt/templates/statemonitor.cpp
brian2/devices/cpp_standalone/templates/statemonitor.cpp
brian2/tests/test_monitor.py

[MRG] Update the `N` variable for `StateMonitor` in the C++/Cython templates

---

brian2/input/spikegeneratorgroup.py
brian2/tests/test_spikegenerator.py

A trivial PR, just adding checks and making sure that the type of `N` is `int` (two issues that came up on the mailing list recently)

[MRG] More checks for arguments of `SpikegeneratorGroup`

---

brian2/tests/__init__.py

This PR should be a simple one for a change :) Tests that raise `NotImplementedError` will now appear as "N" in the test results and by default not make the test suite fail (but you can call`brian2.test(..., fail_for_not_implemented=True)` to change that). Well, that's all, in principle it is very straightforward but there were a few tricky details to get right (in the long run we should just use `nose2`, but for now it is not in anaconda yet, so let's wait until this is the case).

[MRG] Treat `NotImplementedError` as a special test result

---

brian2/codegen/permutation_analysis.py
brian2/tests/test_synapses.py

Most of this pull request consists of changes to the tests to support constants in synaptic statements...
Fixes #620

[MRG] Fix "order dependence" warnings for statements involving constants

---

brian2/input/poissongroup.py
brian2/tests/test_poissongroup.py

[MRG] Allow subgroups of `PoissonGroup`

---

brian2/.gitignore
brian2/spatialneuron/spatialneuron.py
brian2/tests/test_spatialneuron.py

No sure If I had to but this is just to add events arg.

SpatialNeuron Events

---

brian2/monitors/ratemonitor.py
brian2/tests/test_monitor.py
docs_sphinx/user/recording.rst
examples/frompapers/Brunel_Hakim_1999.py
examples/standalone/STDP_standalone.py
examples/synapses/STDP.py

[MRG] Implement `PopulationRateMonitor.smooth_rate`

---

brian2/monitors/spikemonitor.py
brian2/synapses/synapses.py
brian2/tests/test_monitor.py
brian2/tests/test_synapses.py

Fixes #647 (see its discussion for details).

[MRG] Check that the source provided for `SpikeMonitor` is a `SpikeSource`

---

brian2/core/variables.py
brian2/synapses/synapses.py
brian2/tests/test_synapses.py

This needed a few iterations to get things working correctly for subgroups, but now it should be fine and ready to merge.
Fixes #694

[MRG] Fix references to synaptic variables when setting delays on synaptic pathways

---

brian2/tests/test_units.py
brian2/units/fundamentalunits.py

[MRG] Small refactoring of the unit name system to avoid display issues for  compound units involving `Unit(1)`

---

brian2/codegen/runtime/cython_rt/templates/summed_variable.pyx
brian2/codegen/runtime/numpy_rt/templates/summed_variable.py_
brian2/codegen/runtime/weave_rt/templates/summed_variable.cpp
brian2/devices/cpp_standalone/templates/summed_variable.cpp
brian2/synapses/synapses.py
brian2/tests/test_synapses.py
docs_sphinx/introduction/release_notes.rst

Remove hard-coded assumption that summed variable is post-synaptic
Fixes #704

 Remove hard-coded assumption that summed variable is post-synaptic

---

brian2/devices/cpp_standalone/device.py
brian2/tests/test_cpp_standalone.py

A fairly uncontroversial PR, I think :)
Fixes #718

[MRG] Respect the `active` flag in C++ standalone

---

brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
brian2/groups/group.py
brian2/tests/test_neurongroup.py

Fix two minor issues -- see commit messages.

[MRG] Small fixes

---

brian2/synapses/synapses.py

As the title says. Needed for @dokato's export to NeuroML/LEMS.

[MRG] Allow a "device override" for `Synapses.connect`

---

brian2/core/clocks.py
brian2/core/network.py
brian2/tests/test_clocks.py
brian2/tests/test_network.py
docs_sphinx/introduction/release_notes.rst

This should implement what we discussed in #730. Let me know if I forgot anything or misunderstood something.

[MRG] dt and t checks

---

AUTHORS
README.rst
docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/equations.rst
docs_sphinx/user/input.rst
docs_sphinx/user/models.rst
setup.py

[WIP] Finalise 2.0

---

docs_sphinx/user/input.rst

In follow up to #660, I added a minimal example for inhomogeneous Poisson processes to the docs.
I also mention inhomogeneous Poisson on purpose, since this is something bound to be text searched for (at least I did).

Added example for using TimedArray in PoissonGroup

---

.travis.yml
AUTHORS
appveyor.yml
docs_sphinx/introduction/known_issues.rst
docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/computation.rst
docs_sphinx/user/running.rst
tutorials/2-intro-to-brian-synapses.ipynb

A few last documentation updates. After this I'd like to do the 2.0.1 release -- or do you have anything to add?

Documentation updates for 2.0.1

---

brian2/core/network.py
brian2/groups/neurongroup.py
brian2/input/poissongroup.py
brian2/spatialneuron/spatialneuron.py
brian2/synapses/synapses.py
brian2/tests/test_poissongroup.py

Quite unspectacular change, but fixes #783 :-)

Add namespace argument to PoissonGroup

---

brian2/groups/neurongroup.py
brian2/synapses/synapses.py
brian2/tests/test_synapses.py

[MRG] Explicitly check units in equations for synapses

---

brian2/core/variables.py
brian2/devices/cpp_standalone/templates/group_variable_set.cpp
brian2/tests/test_neurongroup.py

[MRG] Simplify `group_variable_set` template in C++ standalone

---

brian2/tests/test_cpp_standalone.py
docs_sphinx/developer/guidelines/testing.rst

[MRG] Correct the testing guidelines for "standalone-only" tests

---

brian2/spatialneuron/spatialneuron.py
brian2/tests/test_spatialneuron.py

Fixes #822 and add a few tests to make sure it does not break again in the future.

[MRG] Fix indexing of subtrees in `SpatialNeuron`

---

brian2/synapses/synapses.py
brian2/tests/test_synapses.py

Issue #781.
This PR adds a check and tests to ensure that during synapse generation, arguments to `range` are always `int`s. If not, it will raise with a **`TypeError`**.

synapse: range(...) arguments type check

---

brian2/codegen/runtime/cython_rt/templates/common.pyx
brian2/codegen/runtime/cython_rt/templates/spatialstateupdate.pyx
brian2/codegen/runtime/numpy_rt/templates/spatialstateupdate.py_
brian2/codegen/runtime/weave_rt/templates/spatialstateupdate.cpp
brian2/devices/cpp_standalone/templates/spatialstateupdate.cpp
brian2/spatialneuron/spatialneuron.py
brian2/tests/test_spatialneuron.py
examples/compartmental/lfp.py

PR to fix #677 
Some caveats apply, as discussed in the issue. I will add the equivalent code to the other backends.

Expose capacitive current in spatial neuron

---

docs_sphinx/advanced/state_update.rst

just to show I can do a pull request

small change in grammar of documentation

---

brian2/codegen/runtime/numpy_rt/templates/spikemonitor.py_
brian2/groups/subgroup.py
brian2/monitors/spikemonitor.py
brian2/tests/test_monitor.py
docs_sphinx/introduction/release_notes.rst

[MRG] Fix bug in SpikeMonitor recording from a subgroup on numpy

---

brian2/codegen/runtime/numpy_rt/templates/synapses_create_generator.py_
brian2/tests/test_synapses.py

[MRG] Fix an error in the synapse generation with numpy

---

brian2/synapses/synapses.py
brian2/tests/test_synapses.py

[MRG] Do not raise an error when using numpy integer types for synaptic indexing

---

brian2/codegen/generators/cython_generator.py
brian2/codegen/translation.py
brian2/core/variables.py
brian2/equations/unitcheck.py
brian2/parsing/expressions.py
brian2/tests/test_parsing.py

Should fix #893 by properly cdef'ing all temporary variables in Cython. See that issue report for more details.

[WIP] Cython types

---

examples/frompapers/Brunel_Wang_2001.py

Add Brunel Wang 2001 example

---

brian2/groups/group.py
brian2/tests/test_subgroup.py

[MRG] Properly support `run_regularly` on subgroups

---

.travis.yml
appveyor.yml
brian2/tests/test_subgroup.py
brian2/tests/test_synapses.py
dev/conda-recipe/meta.yaml
dev/continuous-integration/run_test_suite.py

See https://github.com/brian-team/brian2/pull/957#issuecomment-391792148 -- switch off parallel testing for Cython on the test servers.

[MRG] Fix/workaround Cython test hangs

---

docs_sphinx/introduction/install.rst
docs_sphinx/user/models.rst
docs_sphinx/user/refractoriness.rst
docs_sphinx/user/synapses.rst

Recent questions here and on the mailing list made me aware of a few holes and outdated information in the documentation, this PR should hopefully make a few things clearer.

[MRG] Small doc fixes

---

examples/advanced/float_32_64_benchmark.py

I was curious to know how float32 and float64 compare, so I created a benchmark file for CUBA and COBA. Turns out it makes very little difference but float64 slightly faster.
This PR adds the example.

[MRG] New float32/64 benchmark example

---

brian2/utils/logger.py
docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/synapses.rst

Docs-only change: update release notes for upcoming 2.2 release

[MRG] Release notes 2.2

---

brian2/codegen/generators/cpp_generator.py
brian2/codegen/generators/cython_generator.py
brian2/tests/test_functions.py

See #988, the fix is quite straightforward as suggested by @AI-pha

[MRG] Only add function dependencies once to the code if repeated

---

brian2/codegen/runtime/cython_rt/templates/spikegenerator.pyx
brian2/codegen/runtime/numpy_rt/templates/spikegenerator.py_
brian2/codegen/runtime/weave_rt/templates/spikegenerator.cpp
brian2/devices/cpp_standalone/templates/spikegenerator.cpp
brian2/input/spikegeneratorgroup.py
brian2/tests/test_spikegenerator.py

This should fix #1041, but the applied heuristic (see code) is certainly debatable!

[MRG] Fix #1041

---

brian2/core/functions.py
brian2/tests/test_parsing.py

[MRG] Correctly deal with -inf in equations

---

brian2/equations/equations.py
brian2/stateupdaters/explicit.py
brian2/tests/test_stateupdaters.py
docs_sphinx/introduction/release_notes.rst

Stochastic equation is checked for multiplicative noise by is_constant_over_dt()
Fixes #968

Check multiplicative noise of Stochastic equations

---

brian2/__init__.py

It is very annoying if `check_cache` fails with an error due to missing permissions, moved files, etc., especially given that it can make it impossible for a user to import `brian2`. This somewhat trivial fix just quietly ignores common errors.
Fixes #1081

[MRG] Make `check_cache` more robust

---

tutorials/1-intro-to-brian-neurons.ipynb

Required for tutorial to work in Matplotlib 3.1.0, and at least some versions before it.

Fix to tutorial

---

brian2/tests/__init__.py
brian2/units/fundamentalunits.py

An implementation of "option 2" described in #1120.

[MRG] Exclude numpy doctests from our test suite

---

README.rst
brian2/core/network.py
brian2/groups/neurongroup.py
docs_sphinx/advanced/functions.rst
docs_sphinx/index.rst
docs_sphinx/introduction/code_of_conduct.rst
docs_sphinx/introduction/index.rst
docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/multicompartmental.rst
setup.py

These are the release notes for the release which I'd like to do tomorrow to get it out before the holidays (and the EOL for Python 2!).  I went with 2.3 as the version number, even though it could also be 2.2.3, given that most of the changes are somewhat "behind the scenes". 
The PR also fixes a number of other smallish things in the documentation and the README, but nothing to controversial I think :smile:

[MRG] Release notes 2.3

---

brian2/core/network.py
brian2/tests/test_network.py
docs_sphinx/introduction/release_notes.rst

Via #1151, contained objects are no longer stored in the network
Fixes #1151

[MRG] Do not try to remove contained objects from the network

---

brian2/input/timedarray.py

This just rearranges the code so that other code generations can add implementations for `TimedArray` (same approach that we added for `BinomialFunction` to make it possible to support it in `brian2genn`).
See brian-team/brian2cuda#47

Make TimedArray's implementations extensible

---

brian2/codegen/generators/cpp_generator.py
brian2/codegen/generators/cython_generator.py

See #1205. Generated code could contain duplicated definitions of a function like `rand`, if that function was both used directly and indirectly via a function like `BinomialFunction` which depends on it. The fix is a bit quick&dirty (and there's a lot of code duplication between C++ and Cython), but it fixes a quite serious issue so I'd rather get it out quickly.

Deal with duplicated dependencies

---

docs_sphinx/introduction/release_notes.rst

Please have a last look before I'll go ahead with the release.

Finalize release notes for 2.4 release

---

brian2/tests/features/speed.py
brian2/tests/test_GSL.py
dev/benchmarks/openmp/STDP_standalone.py
docs_sphinx/user/synapses.rst
examples/frompapers/Izhikevich_2007.py
examples/reliability.py
examples/synapses/STDP.py
examples/synapses/nonlinear.py

Hello @mstimberg,
As discussed in #1261, I have modified the names of variables whose name was `input` to prevent confusion amongst users and new developers.

Modified variables with the name input

---

docs_sphinx/user/index.rst
docs_sphinx/user/plotting_functions.rst

Cf. https://brian.discourse.group/t/plotting-of-arbitrary-functions/399﻿

How to plot model functions

---

examples/advanced/COBAHH_approximated.py

Remove membrane voltage ODE as voltage is constant
in the sweep.

Make clearer that membrane voltage is constant

---

brian2/devices/cpp_standalone/device.py

I am running my test suite on a cluster with a job scheduler. Being able to change the `make` and `run` commands allows me to speed up testing significantly e.g. by using `qmake`, which dynamically allocates jobs on the cluster for compilation or by submitting `./main` to a GPU node via `qsub <optiona> main`, which allows me to use non-GPU nodes for compilation. `qmake` and `qsub` are command from the grid engine that does the job scheduling. But this could of course be used similarly for other job schedulers such as `slurm`.
I could of course do this for brian2CUDA specifically, but since I am inheriting the `run` and `compile_source` functions from `CPPStandaloneDevice`, I thought I'll add it there instead.
Should be backward compatible changes. Feel free to change anything you want. :)

Add prefs to change make and run commands in C++ Standalone

---

brian2/devices/cpp_standalone/device.py

Reapply a change from commit 125e591c106 which got lost in a merge

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/dev-requirements.txt
.devcontainer/devcontainer.json
.gitignore
docs_sphinx/developer/index.rst

These are the config files to build a development container automatically after pulling the repo and opening it in VS Code, hopefully lowering the barrier to entry. 
Please have a go and let me know what you think @thesamovar @mstimberg !

Zero to dev

---

examples/frompapers/Tsodyks_Uziel_Markram_2000.py

- Add simulations to reproduce figure 1 from Tsodyks, Uziel and Markram (2000)

Tsodyks Uziel Markram 2000

---

docs_sphinx/introduction/install.rst

Mention the option to install Brian via Spack

---

examples/frompapers/Maass_Natschlaeger_Markram_2002.py

Takes about 10 minutes on 8 i7 cores @ 3 GHz

Reproducing figure 2 of Maass, Natschlaeger and Markram (2002)

---

brian2/core/magic.py
brian2/core/network.py

Fix and sync report_callback documentation

---

docs_sphinx/user/synapses.rst

Remove extra "s" in delay_s_=

---

brian2/tests/test_units.py
brian2/units/fundamentalunits.py

This makes the LaTeX output for `Quantity` arrays more sensible (see #1425) . Before, things looked like this, and big arrays could make the browser work hard to do the MathJax rendering:
With this PR, vectors/matrices will only be printed up to a reasonable size to fit on the screen:
The implementation reuses `np.array2string` and then does a few replacements. Not the most elegant solution, but it means that it follows most of numpy's "print options" automatically. I also finally settled on using `np.get_printoptions['threshold']//100` as the value for the threshold. This is of course quite arbitrary, but this way we don't need a new preference for a niche feature, and users can still influence the behaviour if they really want to:
Fixes #1425

More reasonable LaTeX output for arrays

---

.gitignore

Ignore `.DS_Store` files and slightly reorganise `.gitignore`.

Ignore system files [skip ci]

---

brian2/codegen/optimisation.py
brian2/sphinxext/generate_reference.py
docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/computation.rst

The documentation was no longer building the reference docs (thanks @mpgl for making me aware of the issue). This fixes it and a few other minor documentation issues.

Fix documentation

---

brian2/tests/test_functions.py

Fixes the error that @bdevans saw when running the test suite on Docker: the "external function" test assumed that the test directory was writeable. This changes the test so that it compiles the external function in a temporary directory instead.

Do not assume that the test directory is writeable

---

docs_sphinx/introduction/release_notes.rst
docs_sphinx/user/equations.rst

Release notes for 2.6 and some improvements to the equation documentation

Release notes for 2.6

---

examples/frompapers/Maass_Natschlaeger_Markram_2002.py

Fix incorrect initial values for U

---

brian2/core/network.py
brian2/devices/cpp_standalone/device.py
brian2/tests/test_cpp_standalone.py
brian2/tests/test_network.py

Fixes #1608
Added a condition to check if the duration is negative and raise a ValueError accordingly.

[Fix #1608] : Raises a ValueError for negative duration in run() function

---

README.md

Thank you so much for joining the Collaboration Network! Here is a preview of the badge I've added:
Again, you are welcomed and encouraged to reach out if there is any thing we can do to signal boost your significant efforts! We are at your service.

docs(README): Add neuromorphic computing badge - Collaboration Network
